//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2012-6-8 10:58:31
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml.Serialization;
using System.Collections.Generic;

namespace SinGooCMS.Config
{
    /// <summary>
    /// sys_BaseConfig实体
    /// </summary>
    [Serializable]
    public partial class BaseConfigInfo : JObject, IEntity
    {

        private string _SiteName = string.Empty;

		private string _SiteLogo = string.Empty;

		private string _SiteBanner = string.Empty;

		private string _SiteDomain = string.Empty;

		private string _CopyRight = string.Empty;

		private string _IcpNo = string.Empty;

		private string _DefaultLang = string.Empty;

		private bool _EnabledMobile = false;

		private string _BrowseType = string.Empty;

		private int _GlobalPageSize = 0;

		private string _HtmlNodeFileRule = string.Empty;

		private string _HtmlFileRule = string.Empty;

		private string _HtmlFileExt = string.Empty;

		private string _UserNameRule = string.Empty;

		private string _SysUserName = string.Empty;

		private string _RegAgreement = string.Empty;

		private int _RegGiveIntegral = 0;

		private int _TgIntegral = 0;

		private int _TryLoginTimes = 0;

		private string _CookieTime = string.Empty;

		private bool _VerifycodeForReg = false;

		private bool _VerifycodeForLogin = false;

		private bool _VerifycodeForGetPwd = false;

		private string _ServMailAccount = string.Empty;

		private string _ServMailUserName = string.Empty;

		private string _ServMailUserPwd = string.Empty;

		private string _ServMailSMTP = string.Empty;

		private string _ServMailPort = string.Empty;

		private bool _ServMailIsSSL = false;

		private string _ReciverEMail = string.Empty;

		private string _SMSClass = string.Empty;

		private string _SMSUrl = string.Empty;

		private string _SMSUid = string.Empty;

		private string _SMSPwd = string.Empty;

		private bool _EnableFileUpload = false;

		private string _EnableUploadExt = string.Empty;

		private int _UploadSizeLimit = 0;

		private int _UploadLimit = 0;

		private string _UploadSaveRule = string.Empty;

		private string _ThumbSize = string.Empty;

		private string _ThumbModel = string.Empty;

		private int _WaterMarkPosition = 0;

		private string _WaterMarkType = string.Empty;

		private string _WaterMarkText = string.Empty;

		private int _WaterMarkTextSize = 0;

		private string _WaterMarkTextFont = string.Empty;

		private string _WaterMarkTextColor = string.Empty;

		private string _WaterMarkImage = string.Empty;

		private double _WaterMarkAlpha = 0.0;

		private string _SEOKey = string.Empty;

		private string _SEODescription = string.Empty;

		private string _BadWords = string.Empty;

		private string _BWReplaceWord = string.Empty;

		private decimal _DefKuaidiFee = 0.0m;

		private decimal _DefEMSFee = 0.0m;

		private bool _IsCNTWTrans = false;

		private string _DefaultHtmlEditor = string.Empty;

		private string _STATLink = string.Empty;

		private string _Kuaidi100Key = string.Empty;

		private bool _VisitRec = false;

		private string _ManagerMail = string.Empty;

		private string _ManagerMobile = string.Empty;

		private int _LimitBuyPayExpire = 0;

		private int _BuyPayExpire = 0;

		private int _SignExpire = 0;

		private int _AfterSaleExpire = 0;

		private DateTime _LastModifyDate = new DateTime(1900, 1, 1);

		private static List<string> _listField = null;

		private Dictionary<string, SettingInfo> _CustomSettings;

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public string SiteName
        {
            get
            {
                return this._SiteName;
            }
            set
            {
                this._SiteName = value;
            }
        }

        public string SiteLogo
        {
            get
            {
                return this._SiteLogo;
            }
            set
            {
                this._SiteLogo = value;
            }
        }

        public string SiteBanner
        {
            get
            {
                return this._SiteBanner;
            }
            set
            {
                this._SiteBanner = value;
            }
        }

        public string SiteDomain
        {
            get
            {
                return this._SiteDomain;
            }
            set
            {
                this._SiteDomain = value;
            }
        }

        public string CopyRight
        {
            get
            {
                return this._CopyRight;
            }
            set
            {
                this._CopyRight = value;
            }
        }

        public string IcpNo
        {
            get
            {
                return this._IcpNo;
            }
            set
            {
                this._IcpNo = value;
            }
        }

        public string DefaultLang
        {
            get
            {
                return this._DefaultLang;
            }
            set
            {
                this._DefaultLang = value;
            }
        }

        public bool EnabledMobile
        {
            get
            {
                return this._EnabledMobile;
            }
            set
            {
                this._EnabledMobile = value;
            }
        }

        public string BrowseType
        {
            get
            {
                return this._BrowseType;
            }
            set
            {
                this._BrowseType = value;
            }
        }

        public int GlobalPageSize
        {
            get
            {
                return this._GlobalPageSize;
            }
            set
            {
                this._GlobalPageSize = value;
            }
        }

        public string HtmlNodeFileRule
        {
            get
            {
                return this._HtmlNodeFileRule;
            }
            set
            {
                this._HtmlNodeFileRule = value;
            }
        }

        public string HtmlFileRule
        {
            get
            {
                return this._HtmlFileRule;
            }
            set
            {
                this._HtmlFileRule = value;
            }
        }

        public string HtmlFileExt
        {
            get
            {
                return this._HtmlFileExt;
            }
            set
            {
                this._HtmlFileExt = value;
            }
        }

        public string UserNameRule
        {
            get
            {
                return this._UserNameRule;
            }
            set
            {
                this._UserNameRule = value;
            }
        }

        public string SysUserName
        {
            get
            {
                return this._SysUserName;
            }
            set
            {
                this._SysUserName = value;
            }
        }

        public string RegAgreement
        {
            get
            {
                return this._RegAgreement;
            }
            set
            {
                this._RegAgreement = value;
            }
        }

        public int RegGiveIntegral
        {
            get
            {
                return this._RegGiveIntegral;
            }
            set
            {
                this._RegGiveIntegral = value;
            }
        }

        public int TgIntegral
        {
            get
            {
                return this._TgIntegral;
            }
            set
            {
                this._TgIntegral = value;
            }
        }

        public int TryLoginTimes
        {
            get
            {
                return this._TryLoginTimes;
            }
            set
            {
                this._TryLoginTimes = value;
            }
        }

        public string CookieTime
        {
            get
            {
                return this._CookieTime;
            }
            set
            {
                this._CookieTime = value;
            }
        }

        public bool VerifycodeForReg
        {
            get
            {
                return this._VerifycodeForReg;
            }
            set
            {
                this._VerifycodeForReg = value;
            }
        }

        public bool VerifycodeForLogin
        {
            get
            {
                return this._VerifycodeForLogin;
            }
            set
            {
                this._VerifycodeForLogin = value;
            }
        }

        public bool VerifycodeForGetPwd
        {
            get
            {
                return this._VerifycodeForGetPwd;
            }
            set
            {
                this._VerifycodeForGetPwd = value;
            }
        }

        public string ServMailAccount
        {
            get
            {
                return this._ServMailAccount;
            }
            set
            {
                this._ServMailAccount = value;
            }
        }

        public string ServMailUserName
        {
            get
            {
                return this._ServMailUserName;
            }
            set
            {
                this._ServMailUserName = value;
            }
        }

        public string ServMailUserPwd
        {
            get
            {
                return this._ServMailUserPwd;
            }
            set
            {
                this._ServMailUserPwd = value;
            }
        }

        public string ServMailSMTP
        {
            get
            {
                return this._ServMailSMTP;
            }
            set
            {
                this._ServMailSMTP = value;
            }
        }

        public string ServMailPort
        {
            get
            {
                return this._ServMailPort;
            }
            set
            {
                this._ServMailPort = value;
            }
        }

        public bool ServMailIsSSL
        {
            get
            {
                return this._ServMailIsSSL;
            }
            set
            {
                this._ServMailIsSSL = value;
            }
        }

        public string ReciverEMail
        {
            get
            {
                return this._ReciverEMail;
            }
            set
            {
                this._ReciverEMail = value;
            }
        }

        public string SMSClass
        {
            get
            {
                return this._SMSClass;
            }
            set
            {
                this._SMSClass = value;
            }
        }

        public string SMSUrl
        {
            get
            {
                return this._SMSUrl;
            }
            set
            {
                this._SMSUrl = value;
            }
        }

        public string SMSUid
        {
            get
            {
                return this._SMSUid;
            }
            set
            {
                this._SMSUid = value;
            }
        }

        public string SMSPwd
        {
            get
            {
                return this._SMSPwd;
            }
            set
            {
                this._SMSPwd = value;
            }
        }

        public bool EnableFileUpload
        {
            get
            {
                return this._EnableFileUpload;
            }
            set
            {
                this._EnableFileUpload = value;
            }
        }

        public string EnableUploadExt
        {
            get
            {
                return this._EnableUploadExt;
            }
            set
            {
                this._EnableUploadExt = value;
            }
        }

        public int UploadSizeLimit
        {
            get
            {
                return this._UploadSizeLimit;
            }
            set
            {
                this._UploadSizeLimit = value;
            }
        }

        public int UploadLimit
        {
            get
            {
                return this._UploadLimit;
            }
            set
            {
                this._UploadLimit = value;
            }
        }

        public string UploadSaveRule
        {
            get
            {
                return this._UploadSaveRule;
            }
            set
            {
                this._UploadSaveRule = value;
            }
        }

        public string ThumbSize
        {
            get
            {
                return this._ThumbSize;
            }
            set
            {
                this._ThumbSize = value;
            }
        }

        public string ThumbModel
        {
            get
            {
                return this._ThumbModel;
            }
            set
            {
                this._ThumbModel = value;
            }
        }

        public int WaterMarkPosition
        {
            get
            {
                return this._WaterMarkPosition;
            }
            set
            {
                this._WaterMarkPosition = value;
            }
        }

        public string WaterMarkType
        {
            get
            {
                return this._WaterMarkType;
            }
            set
            {
                this._WaterMarkType = value;
            }
        }

        public string WaterMarkText
        {
            get
            {
                return this._WaterMarkText;
            }
            set
            {
                this._WaterMarkText = value;
            }
        }

        public int WaterMarkTextSize
        {
            get
            {
                return this._WaterMarkTextSize;
            }
            set
            {
                this._WaterMarkTextSize = value;
            }
        }

        public string WaterMarkTextFont
        {
            get
            {
                return this._WaterMarkTextFont;
            }
            set
            {
                this._WaterMarkTextFont = value;
            }
        }

        public string WaterMarkTextColor
        {
            get
            {
                return this._WaterMarkTextColor;
            }
            set
            {
                this._WaterMarkTextColor = value;
            }
        }

        public string WaterMarkImage
        {
            get
            {
                return this._WaterMarkImage;
            }
            set
            {
                this._WaterMarkImage = value;
            }
        }

        public double WaterMarkAlpha
        {
            get
            {
                return this._WaterMarkAlpha;
            }
            set
            {
                this._WaterMarkAlpha = value;
            }
        }

        public string SEOKey
        {
            get
            {
                return this._SEOKey;
            }
            set
            {
                this._SEOKey = value;
            }
        }

        public string SEODescription
        {
            get
            {
                return this._SEODescription;
            }
            set
            {
                this._SEODescription = value;
            }
        }

        public string BadWords
        {
            get
            {
                return this._BadWords;
            }
            set
            {
                this._BadWords = value;
            }
        }

        public string BWReplaceWord
        {
            get
            {
                return this._BWReplaceWord;
            }
            set
            {
                this._BWReplaceWord = value;
            }
        }

        public decimal DefKuaidiFee
        {
            get
            {
                return this._DefKuaidiFee;
            }
            set
            {
                this._DefKuaidiFee = value;
            }
        }

        public decimal DefEMSFee
        {
            get
            {
                return this._DefEMSFee;
            }
            set
            {
                this._DefEMSFee = value;
            }
        }

        public bool IsCNTWTrans
        {
            get
            {
                return this._IsCNTWTrans;
            }
            set
            {
                this._IsCNTWTrans = value;
            }
        }

        public string DefaultHtmlEditor
        {
            get
            {
                return this._DefaultHtmlEditor;
            }
            set
            {
                this._DefaultHtmlEditor = value;
            }
        }

        public string STATLink
        {
            get
            {
                return this._STATLink;
            }
            set
            {
                this._STATLink = value;
            }
        }

        public string Kuaidi100Key
        {
            get
            {
                return this._Kuaidi100Key;
            }
            set
            {
                this._Kuaidi100Key = value;
            }
        }

        public bool VisitRec
        {
            get
            {
                return this._VisitRec;
            }
            set
            {
                this._VisitRec = value;
            }
        }

        public string ManagerMail
        {
            get
            {
                return this._ManagerMail;
            }
            set
            {
                this._ManagerMail = value;
            }
        }

        public string ManagerMobile
        {
            get
            {
                return this._ManagerMobile;
            }
            set
            {
                this._ManagerMobile = value;
            }
        }

        public int LimitBuyPayExpire
        {
            get
            {
                return this._LimitBuyPayExpire;
            }
            set
            {
                this._LimitBuyPayExpire = value;
            }
        }

        public int BuyPayExpire
        {
            get
            {
                return this._BuyPayExpire;
            }
            set
            {
                this._BuyPayExpire = value;
            }
        }

        public int SignExpire
        {
            get
            {
                return this._SignExpire;
            }
            set
            {
                this._SignExpire = value;
            }
        }

        public int AfterSaleExpire
        {
            get
            {
                return this._AfterSaleExpire;
            }
            set
            {
                this._AfterSaleExpire = value;
            }
        }

        public DateTime LastModifyDate
        {
            get
            {
                return this._LastModifyDate;
            }
            set
            {
                this._LastModifyDate = value;
            }
        }

        public string DBTableName
        {
            get
            {
                return "sys_BaseConfig";
            }
        }

        public string PKName
        {
            get
            {
                return "";
            }
        }

        public string Fields
        {
            get
            {
                return "SiteName,SiteLogo,SiteBanner,SiteDomain,CopyRight,IcpNo,DefaultLang,EnabledMobile,BrowseType,GlobalPageSize,HtmlNodeFileRule,HtmlFileRule,HtmlFileExt,UserNameRule,SysUserName,RegAgreement,RegGiveIntegral,TgIntegral,TryLoginTimes,CookieTime,VerifycodeForReg,VerifycodeForLogin,VerifycodeForGetPwd,ServMailAccount,ServMailUserName,ServMailUserPwd,ServMailSMTP,ServMailPort,ServMailIsSSL,ReciverEMail,SMSClass,SMSUrl,SMSUid,SMSPwd,EnableFileUpload,EnableUploadExt,UploadSizeLimit,UploadLimit,UploadSaveRule,ThumbSize,ThumbModel,WaterMarkPosition,WaterMarkType,WaterMarkText,WaterMarkTextSize,WaterMarkTextFont,WaterMarkTextColor,WaterMarkImage,WaterMarkAlpha,SEOKey,SEODescription,BadWords,BWReplaceWord,DefKuaidiFee,DefEMSFee,IsCNTWTrans,DefaultHtmlEditor,STATLink,Kuaidi100Key,VisitRec,ManagerMail,ManagerMobile,LimitBuyPayExpire,BuyPayExpire,SignExpire,AfterSaleExpire,LastModifyDate";
            }
        }

        public List<string> FieldList
        {
            get
            {
                if (BaseConfigInfo._listField == null)
                {
                    BaseConfigInfo._listField = new List<string>();
                    BaseConfigInfo._listField.Add("SiteName");
                    BaseConfigInfo._listField.Add("SiteLogo");
                    BaseConfigInfo._listField.Add("SiteBanner");
                    BaseConfigInfo._listField.Add("SiteDomain");
                    BaseConfigInfo._listField.Add("CopyRight");
                    BaseConfigInfo._listField.Add("IcpNo");
                    BaseConfigInfo._listField.Add("DefaultLang");
                    BaseConfigInfo._listField.Add("EnabledMobile");
                    BaseConfigInfo._listField.Add("BrowseType");
                    BaseConfigInfo._listField.Add("GlobalPageSize");
                    BaseConfigInfo._listField.Add("HtmlNodeFileRule");
                    BaseConfigInfo._listField.Add("HtmlFileRule");
                    BaseConfigInfo._listField.Add("HtmlFileExt");
                    BaseConfigInfo._listField.Add("UserNameRule");
                    BaseConfigInfo._listField.Add("SysUserName");
                    BaseConfigInfo._listField.Add("RegAgreement");
                    BaseConfigInfo._listField.Add("RegGiveIntegral");
                    BaseConfigInfo._listField.Add("TgIntegral");
                    BaseConfigInfo._listField.Add("TryLoginTimes");
                    BaseConfigInfo._listField.Add("CookieTime");
                    BaseConfigInfo._listField.Add("VerifycodeForReg");
                    BaseConfigInfo._listField.Add("VerifycodeForLogin");
                    BaseConfigInfo._listField.Add("VerifycodeForGetPwd");
                    BaseConfigInfo._listField.Add("ServMailAccount");
                    BaseConfigInfo._listField.Add("ServMailUserName");
                    BaseConfigInfo._listField.Add("ServMailUserPwd");
                    BaseConfigInfo._listField.Add("ServMailSMTP");
                    BaseConfigInfo._listField.Add("ServMailPort");
                    BaseConfigInfo._listField.Add("ServMailIsSSL");
                    BaseConfigInfo._listField.Add("ReciverEMail");
                    BaseConfigInfo._listField.Add("SMSClass");
                    BaseConfigInfo._listField.Add("SMSUrl");
                    BaseConfigInfo._listField.Add("SMSUid");
                    BaseConfigInfo._listField.Add("SMSPwd");
                    BaseConfigInfo._listField.Add("EnableFileUpload");
                    BaseConfigInfo._listField.Add("EnableUploadExt");
                    BaseConfigInfo._listField.Add("UploadSizeLimit");
                    BaseConfigInfo._listField.Add("UploadLimit");
                    BaseConfigInfo._listField.Add("UploadSaveRule");
                    BaseConfigInfo._listField.Add("ThumbSize");
                    BaseConfigInfo._listField.Add("ThumbModel");
                    BaseConfigInfo._listField.Add("WaterMarkPosition");
                    BaseConfigInfo._listField.Add("WaterMarkType");
                    BaseConfigInfo._listField.Add("WaterMarkText");
                    BaseConfigInfo._listField.Add("WaterMarkTextSize");
                    BaseConfigInfo._listField.Add("WaterMarkTextFont");
                    BaseConfigInfo._listField.Add("WaterMarkTextColor");
                    BaseConfigInfo._listField.Add("WaterMarkImage");
                    BaseConfigInfo._listField.Add("WaterMarkAlpha");
                    BaseConfigInfo._listField.Add("SEOKey");
                    BaseConfigInfo._listField.Add("SEODescription");
                    BaseConfigInfo._listField.Add("BadWords");
                    BaseConfigInfo._listField.Add("BWReplaceWord");
                    BaseConfigInfo._listField.Add("DefKuaidiFee");
                    BaseConfigInfo._listField.Add("DefEMSFee");
                    BaseConfigInfo._listField.Add("IsCNTWTrans");
                    BaseConfigInfo._listField.Add("DefaultHtmlEditor");
                    BaseConfigInfo._listField.Add("STATLink");
                    BaseConfigInfo._listField.Add("Kuaidi100Key");
                    BaseConfigInfo._listField.Add("VisitRec");
                    BaseConfigInfo._listField.Add("ManagerMail");
                    BaseConfigInfo._listField.Add("ManagerMobile");
                    BaseConfigInfo._listField.Add("LimitBuyPayExpire");
                    BaseConfigInfo._listField.Add("BuyPayExpire");
                    BaseConfigInfo._listField.Add("SignExpire");
                    BaseConfigInfo._listField.Add("AfterSaleExpire");
                    BaseConfigInfo._listField.Add("LastModifyDate");
                }
                return BaseConfigInfo._listField;
            }
        }

        [XmlIgnore]
        public Dictionary<string, SettingInfo> CustomSetting
        {
            get
            {
                if (this._CustomSettings == null)
                {
                    this._CustomSettings = SettingProvider.GetCacheSettingDictionary();
                }
                return this._CustomSettings;
            }
        }

        public string this[string strKey]
        {
            get
            {
                string result;
                if (this.CustomSetting.ContainsKey(strKey))
                {
                    result = this.CustomSetting[strKey].KeyValue;
                }
                else
                {
                    result = string.Empty;
                }
                return result;
            }
        }

        public SettingInfo Get(string strkey)
        {
            SettingInfo result;
            if (this.CustomSetting.ContainsKey(strkey))
            {
                result = this.CustomSetting[strkey];
            }
            else
            {
                result = null;
            }
            return result;
        }
    }
}