//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-11-3 17:39:06
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Config
{
    /// <summary>
    /// 自定义设置实体类
    /// </summary>
    [Serializable]
    public partial class SettingInfo : JObject, IEntity
    {
        #region 私有字段

        private System.Int32 _AutoID = 0;

        private System.Int32 _CateID = 0;

        private System.String _KeyName = string.Empty;

        private System.String _KeyValue = string.Empty;

        private System.String _KeyDesc = string.Empty;

        private System.String _Tip = string.Empty;

        private System.String _ControlType = string.Empty;

        private System.String _DataType = string.Empty;

        private System.Int32 _DataLength = 0;

        private System.String _DefaultValue = string.Empty;

        private System.String _Setting = string.Empty;

        private System.Int32 _Sort = 0;

        private System.Boolean _IsUsing = false;

        private System.Boolean _IsSystem = false;

        private System.DateTime _AutoTimeStamp = new DateTime(1900, 1, 1);

        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public SettingInfo()
        {
            //
        }

        #region 公共属性

        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }

        /// <summary>
        /// 类别ID
        /// </summary>
        public System.Int32 CateID
        {
            get { return _CateID; }
            set { _CateID = value; }
        }

        /// <summary>
        /// 键名称
        /// </summary>
        public System.String KeyName
        {
            get { return _KeyName; }
            set { _KeyName = value; }
        }

        /// <summary>
        /// 键值
        /// </summary>
        public System.String KeyValue
        {
            get { return _KeyValue; }
            set { _KeyValue = value; }
        }

        /// <summary>
        /// 描述
        /// </summary>
        public System.String KeyDesc
        {
            get { return _KeyDesc; }
            set { _KeyDesc = value; }
        }

        /// <summary>
        /// 提示
        /// </summary>
        public System.String Tip
        {
            get { return _Tip; }
            set { _Tip = value; }
        }

        /// <summary>
        /// 控件类型
        /// </summary>
        public System.String ControlType
        {
            get { return _ControlType; }
            set { _ControlType = value; }
        }

        /// <summary>
        /// 数据类型
        /// </summary>
        public System.String DataType
        {
            get { return _DataType; }
            set { _DataType = value; }
        }

        /// <summary>
        /// 数据长度
        /// </summary>
        public System.Int32 DataLength
        {
            get { return _DataLength; }
            set { _DataLength = value; }
        }

        /// <summary>
        /// 默认值
        /// </summary>
        public System.String DefaultValue
        {
            get { return _DefaultValue; }
            set { _DefaultValue = value; }
        }

        /// <summary>
        /// 设置
        /// </summary>
        public System.String Setting
        {
            get { return _Setting; }
            set { _Setting = value; }
        }

        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort
        {
            get { return _Sort; }
            set { _Sort = value; }
        }

        /// <summary>
        /// 是否启用
        /// </summary>
        public System.Boolean IsUsing
        {
            get { return _IsUsing; }
            set { _IsUsing = value; }
        }

        /// <summary>
        /// 是否系统项
        /// </summary>
        public System.Boolean IsSystem
        {
            get { return _IsSystem; }
            set { _IsSystem = value; }
        }

        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }

        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "sys_Setting";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,CateID,KeyName,KeyValue,KeyDesc,Tip,ControlType,DataType,DataLength,DefaultValue,Setting,Sort,IsUsing,IsSystem,AutoTimeStamp";
            }
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {
                    _listField = new List<System.String>();

                    _listField.Add("AutoID");

                    _listField.Add("CateID");

                    _listField.Add("KeyName");

                    _listField.Add("KeyValue");

                    _listField.Add("KeyDesc");

                    _listField.Add("Tip");

                    _listField.Add("ControlType");

                    _listField.Add("DataType");

                    _listField.Add("DataLength");

                    _listField.Add("DefaultValue");

                    _listField.Add("Setting");

                    _listField.Add("Sort");

                    _listField.Add("IsUsing");

                    _listField.Add("IsSystem");

                    _listField.Add("AutoTimeStamp");

                }

                return _listField;
            }
        }

        #endregion

    }
}