//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:11
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 账户明细实体类
    /// </summary>
    [Serializable]
    public partial class AccountDetailInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _UserID=0;
        
        private System.String _UserName=string.Empty;
        
        private System.String _Unit=string.Empty;
        
        private System.Double _Before=0.0d;
        
        private System.Double _OpValue=0.0d;
        
        private System.Int32 _OpType=0;
        
        private System.Double _After=0.0d;
        
        private System.String _Remark=string.Empty;
        
        private System.String _Operator=string.Empty;
        
        private System.DateTime _OperateDate=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public AccountDetailInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 会员ID
        /// </summary>
        public System.Int32 UserID 
        {
            get { return _UserID; }
            set { _UserID = value; }
        }
        
        /// <summary>
        /// 会员名称
        /// </summary>
        public System.String UserName 
        {
            get { return _UserName; }
            set { _UserName = value; }
        }
        
        /// <summary>
        /// 单位
        /// </summary>
        public System.String Unit 
        {
            get { return _Unit; }
            set { _Unit = value; }
        }
        
        /// <summary>
        /// 操作前数值
        /// </summary>
        public System.Double Before 
        {
            get { return _Before; }
            set { _Before = value; }
        }
        
        /// <summary>
        /// 增加数值
        /// </summary>
        public System.Double OpValue 
        {
            get { return _OpValue; }
            set { _OpValue = value; }
        }
        
        /// <summary>
        /// 操作类型
        /// </summary>
        public System.Int32 OpType 
        {
            get { return _OpType; }
            set { _OpType = value; }
        }
        
        /// <summary>
        /// 操作后数值
        /// </summary>
        public System.Double After 
        {
            get { return _After; }
            set { _After = value; }
        }
        
        /// <summary>
        /// 说明
        /// </summary>
        public System.String Remark 
        {
            get { return _Remark; }
            set { _Remark = value; }
        }
        
        /// <summary>
        /// 操作者
        /// </summary>
        public System.String Operator 
        {
            get { return _Operator; }
            set { _Operator = value; }
        }
        
        /// <summary>
        /// 操作时间
        /// </summary>
        public System.DateTime OperateDate 
        {
            get { return _OperateDate; }
            set { _OperateDate = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_AccountDetail";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,UserID,UserName,Unit,Before,OpValue,OpType,After,Remark,Operator,OperateDate";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("UserID");
                    
                    _listField.Add("UserName");
                    
                    _listField.Add("Unit");
                    
                    _listField.Add("Before");
                    
                    _listField.Add("OpValue");
                    
                    _listField.Add("OpType");
                    
                    _listField.Add("After");
                    
                    _listField.Add("Remark");
                    
                    _listField.Add("Operator");
                    
                    _listField.Add("OperateDate");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}