//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:12
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 广告位实体类
    /// </summary>
    [Serializable]
    public partial class AdPlaceInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _PlaceName=string.Empty;
        
        private System.Int32 _Width=0;
        
        private System.Int32 _Height=0;
        
        private System.Decimal _Price=0.0m;
        
        private System.String _TemplateFile=string.Empty;
        
        private System.String _PlaceDesc=string.Empty;
        
        private System.Int32 _Sort=0;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public AdPlaceInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 广告位名称
        /// </summary>
        public System.String PlaceName 
        {
            get { return _PlaceName; }
            set { _PlaceName = value; }
        }
        
        /// <summary>
        /// 广告位长度
        /// </summary>
        public System.Int32 Width 
        {
            get { return _Width; }
            set { _Width = value; }
        }
        
        /// <summary>
        /// 广告位宽度
        /// </summary>
        public System.Int32 Height 
        {
            get { return _Height; }
            set { _Height = value; }
        }
        
        /// <summary>
        /// 价格
        /// </summary>
        public System.Decimal Price 
        {
            get { return _Price; }
            set { _Price = value; }
        }
        
        /// <summary>
        /// 模板文件
        /// </summary>
        public System.String TemplateFile 
        {
            get { return _TemplateFile; }
            set { _TemplateFile = value; }
        }
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String PlaceDesc 
        {
            get { return _PlaceDesc; }
            set { _PlaceDesc = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 语言版本
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_AdPlace";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,PlaceName,Width,Height,Price,TemplateFile,PlaceDesc,Sort,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("PlaceName");
                    
                    _listField.Add("Width");
                    
                    _listField.Add("Height");
                    
                    _listField.Add("Price");
                    
                    _listField.Add("TemplateFile");
                    
                    _listField.Add("PlaceDesc");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}