//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:13
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 广告实体类
    /// </summary>
    [Serializable]
    public partial class AdsInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _PlaceID=0;
        
        private System.String _AdName=string.Empty;
        
        private System.Int32 _AdType=0;
        
        private System.String _AdLink=string.Empty;
        
        private System.DateTime _BeginDate=new DateTime(1900, 1, 1);
        
        private System.DateTime _EndDate=new DateTime(1900, 1, 1);
        
        private System.String _AdText=string.Empty;
        
        private System.String _AdMediaPath=string.Empty;
        
        private System.String _AdDesc=string.Empty;
        
        private System.Boolean _IsNewWin=false;
        
        private System.Int32 _Hit=0;
        
        private System.Boolean _IsAudit=false;
        
        private System.Int32 _Sort=0;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public AdsInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 广告位ID
        /// </summary>
        public System.Int32 PlaceID 
        {
            get { return _PlaceID; }
            set { _PlaceID = value; }
        }
        
        /// <summary>
        /// 广告名称
        /// </summary>
        public System.String AdName 
        {
            get { return _AdName; }
            set { _AdName = value; }
        }
        
        /// <summary>
        /// 广告类型
        /// </summary>
        public System.Int32 AdType 
        {
            get { return _AdType; }
            set { _AdType = value; }
        }
        
        /// <summary>
        /// 链接地址
        /// </summary>
        public System.String AdLink 
        {
            get { return _AdLink; }
            set { _AdLink = value; }
        }
        
        /// <summary>
        /// 广告开始时间
        /// </summary>
        public System.DateTime BeginDate 
        {
            get { return _BeginDate; }
            set { _BeginDate = value; }
        }
        
        /// <summary>
        /// 广告结束时间
        /// </summary>
        public System.DateTime EndDate 
        {
            get { return _EndDate; }
            set { _EndDate = value; }
        }
        
        /// <summary>
        /// 广告文本
        /// </summary>
        public System.String AdText 
        {
            get { return _AdText; }
            set { _AdText = value; }
        }
        
        /// <summary>
        /// 广告媒体路径
        /// </summary>
        public System.String AdMediaPath 
        {
            get { return _AdMediaPath; }
            set { _AdMediaPath = value; }
        }
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String AdDesc 
        {
            get { return _AdDesc; }
            set { _AdDesc = value; }
        }
        
        /// <summary>
        /// 是否新开窗口
        /// </summary>
        public System.Boolean IsNewWin 
        {
            get { return _IsNewWin; }
            set { _IsNewWin = value; }
        }
        
        /// <summary>
        /// 点击数
        /// </summary>
        public System.Int32 Hit 
        {
            get { return _Hit; }
            set { _Hit = value; }
        }
        
        /// <summary>
        /// 是否审核
        /// </summary>
        public System.Boolean IsAudit 
        {
            get { return _IsAudit; }
            set { _IsAudit = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 语言版本
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_Ads";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,PlaceID,AdName,AdType,AdLink,BeginDate,EndDate,AdText,AdMediaPath,AdDesc,IsNewWin,Hit,IsAudit,Sort,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("PlaceID");
                    
                    _listField.Add("AdName");
                    
                    _listField.Add("AdType");
                    
                    _listField.Add("AdLink");
                    
                    _listField.Add("BeginDate");
                    
                    _listField.Add("EndDate");
                    
                    _listField.Add("AdText");
                    
                    _listField.Add("AdMediaPath");
                    
                    _listField.Add("AdDesc");
                    
                    _listField.Add("IsNewWin");
                    
                    _listField.Add("Hit");
                    
                    _listField.Add("IsAudit");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}