//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:43
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 拍卖记录实体类
    /// </summary>
    [Serializable]
    public partial class AuctionLogInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _AuctionID=0;
        
        private System.Int32 _UserID=0;
        
        private System.String _UserName=string.Empty;
        
        private System.Decimal _BeforeAmount=0.0m;
        
        private System.Decimal _Amount=0.0m;
        
        private System.Decimal _AfterAmount=0.0m;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public AuctionLogInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 拍卖编号
        /// </summary>
        public System.Int32 AuctionID 
        {
            get { return _AuctionID; }
            set { _AuctionID = value; }
        }
        
        /// <summary>
        /// 会员ID
        /// </summary>
        public System.Int32 UserID 
        {
            get { return _UserID; }
            set { _UserID = value; }
        }
        
        /// <summary>
        /// 会员名称
        /// </summary>
        public System.String UserName 
        {
            get { return _UserName; }
            set { _UserName = value; }
        }
        
        /// <summary>
        /// 出价前金额
        /// </summary>
        public System.Decimal BeforeAmount 
        {
            get { return _BeforeAmount; }
            set { _BeforeAmount = value; }
        }
        
        /// <summary>
        /// 出价金额
        /// </summary>
        public System.Decimal Amount 
        {
            get { return _Amount; }
            set { _Amount = value; }
        }
        
        /// <summary>
        /// 出价后金额
        /// </summary>
        public System.Decimal AfterAmount 
        {
            get { return _AfterAmount; }
            set { _AfterAmount = value; }
        }
        
        /// <summary>
        /// 时间
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_AuctionLog";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,AuctionID,UserID,UserName,BeforeAmount,Amount,AfterAmount,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("AuctionID");
                    
                    _listField.Add("UserID");
                    
                    _listField.Add("UserName");
                    
                    _listField.Add("BeforeAmount");
                    
                    _listField.Add("Amount");
                    
                    _listField.Add("AfterAmount");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}