//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2015-9-17 13:39:22
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 微信自动回复实体类
    /// </summary>
    [Serializable]
    public partial class AutoRlyInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _RlyType=string.Empty;
        
        private System.String _MsgKey=string.Empty;
        
        private System.String _MsgText=string.Empty;
        
        private System.String _Description=string.Empty;
        
        private System.String _MediaPath=string.Empty;
        
        private System.String _LinkUrl=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public AutoRlyInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 类型
        /// </summary>
        public System.String RlyType 
        {
            get { return _RlyType; }
            set { _RlyType = value; }
        }
        
        /// <summary>
        /// 关键字
        /// </summary>
        public System.String MsgKey 
        {
            get { return _MsgKey; }
            set { _MsgKey = value; }
        }
        
        /// <summary>
        /// 文本
        /// </summary>
        public System.String MsgText 
        {
            get { return _MsgText; }
            set { _MsgText = value; }
        }
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String Description 
        {
            get { return _Description; }
            set { _Description = value; }
        }
        
        /// <summary>
        /// 图片、媒体路径
        /// </summary>
        public System.String MediaPath 
        {
            get { return _MediaPath; }
            set { _MediaPath = value; }
        }
        
        /// <summary>
        /// 链接
        /// </summary>
        public System.String LinkUrl 
        {
            get { return _LinkUrl; }
            set { _LinkUrl = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "weixin_AutoRly";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,RlyType,MsgKey,MsgText,Description,MediaPath,LinkUrl,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("RlyType");
                    
                    _listField.Add("MsgKey");
                    
                    _listField.Add("MsgText");
                    
                    _listField.Add("Description");
                    
                    _listField.Add("MediaPath");
                    
                    _listField.Add("LinkUrl");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}