//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:13
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 后台管理目录实体类
    /// </summary>
    [Serializable]
    public partial class CatalogInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _CatalogName=string.Empty;
        
        private System.String _CatalogCode=string.Empty;
        
        private System.String _ImagePath=string.Empty;
        
        private System.Boolean _IsSystem=false;
        
        private System.String _Remark=string.Empty;
        
        private System.Int32 _Sort=0;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public CatalogInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 目录名称
        /// </summary>
        public System.String CatalogName 
        {
            get { return _CatalogName; }
            set { _CatalogName = value; }
        }
        
        /// <summary>
        /// 目录编号
        /// </summary>
        public System.String CatalogCode 
        {
            get { return _CatalogCode; }
            set { _CatalogCode = value; }
        }
        
        /// <summary>
        /// 图标路径
        /// </summary>
        public System.String ImagePath 
        {
            get { return _ImagePath; }
            set { _ImagePath = value; }
        }
        
        /// <summary>
        /// 是否系统目录
        /// </summary>
        public System.Boolean IsSystem 
        {
            get { return _IsSystem; }
            set { _IsSystem = value; }
        }
        
        /// <summary>
        /// 备注
        /// </summary>
        public System.String Remark 
        {
            get { return _Remark; }
            set { _Remark = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 创建日期
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_Catalog";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,CatalogName,CatalogCode,ImagePath,IsSystem,Remark,Sort,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("CatalogName");
                    
                    _listField.Add("CatalogCode");
                    
                    _listField.Add("ImagePath");
                    
                    _listField.Add("IsSystem");
                    
                    _listField.Add("Remark");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}