//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:14
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 评论实体类
    /// </summary>
    [Serializable]
    public partial class CommentInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _ContID=0;
        
        private System.String _ContName=string.Empty;
        
        private System.Int32 _UserID=0;
        
        private System.String _UserName=string.Empty;
        
        private System.Int32 _ReplyID=0;
        
        private System.String _Title=string.Empty;
        
        private System.String _Content=string.Empty;
        
        private System.String _IPAddress=string.Empty;
        
        private System.String _IPArea=string.Empty;
        
        private System.Boolean _EnableAnonymous=false;
        
        private System.Boolean _IsReply=false;
        
        private System.Boolean _IsAudit=false;
        
        private System.Int32 _Ding=0;
        
        private System.Int32 _Cai=0;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public CommentInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 内容ID
        /// </summary>
        public System.Int32 ContID 
        {
            get { return _ContID; }
            set { _ContID = value; }
        }
        
        /// <summary>
        /// 内容标题
        /// </summary>
        public System.String ContName 
        {
            get { return _ContName; }
            set { _ContName = value; }
        }
        
        /// <summary>
        /// 用户ID
        /// </summary>
        public System.Int32 UserID 
        {
            get { return _UserID; }
            set { _UserID = value; }
        }
        
        /// <summary>
        /// 用户名称
        /// </summary>
        public System.String UserName 
        {
            get { return _UserName; }
            set { _UserName = value; }
        }
        
        /// <summary>
        /// 回复评论ID
        /// </summary>
        public System.Int32 ReplyID 
        {
            get { return _ReplyID; }
            set { _ReplyID = value; }
        }
        
        /// <summary>
        /// 标题
        /// </summary>
        public System.String Title 
        {
            get { return _Title; }
            set { _Title = value; }
        }
        
        /// <summary>
        /// 内容
        /// </summary>
        public System.String Content 
        {
            get { return _Content; }
            set { _Content = value; }
        }
        
        /// <summary>
        /// IP地址
        /// </summary>
        public System.String IPAddress 
        {
            get { return _IPAddress; }
            set { _IPAddress = value; }
        }
        
        /// <summary>
        /// IP地域
        /// </summary>
        public System.String IPArea 
        {
            get { return _IPArea; }
            set { _IPArea = value; }
        }
        
        /// <summary>
        /// 是否支持匿名评论
        /// </summary>
        public System.Boolean EnableAnonymous 
        {
            get { return _EnableAnonymous; }
            set { _EnableAnonymous = value; }
        }
        
        /// <summary>
        /// 是否回复
        /// </summary>
        public System.Boolean IsReply 
        {
            get { return _IsReply; }
            set { _IsReply = value; }
        }
        
        /// <summary>
        /// 是否审核
        /// </summary>
        public System.Boolean IsAudit 
        {
            get { return _IsAudit; }
            set { _IsAudit = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 Ding 
        {
            get { return _Ding; }
            set { _Ding = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 Cai 
        {
            get { return _Cai; }
            set { _Cai = value; }
        }
        
        /// <summary>
        /// 语言版本
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 发布时间
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_Comment";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,ContID,ContName,UserID,UserName,ReplyID,Title,Content,IPAddress,IPArea,EnableAnonymous,IsReply,IsAudit,Ding,Cai,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("ContID");
                    
                    _listField.Add("ContName");
                    
                    _listField.Add("UserID");
                    
                    _listField.Add("UserName");
                    
                    _listField.Add("ReplyID");
                    
                    _listField.Add("Title");
                    
                    _listField.Add("Content");
                    
                    _listField.Add("IPAddress");
                    
                    _listField.Add("IPArea");
                    
                    _listField.Add("EnableAnonymous");
                    
                    _listField.Add("IsReply");
                    
                    _listField.Add("IsAudit");
                    
                    _listField.Add("Ding");
                    
                    _listField.Add("Cai");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}