//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:15
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 文章评论顶踩日志实体类
    /// </summary>
    [Serializable]
    public partial class CommentActiveLogInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _UserID=0;
        
        private System.String _UserName=string.Empty;
        
        private System.Int32 _ContentID=0;
        
        private System.Int32 _CommentID=0;
        
        private System.String _IPAddress=string.Empty;
        
        private System.String _IPArea=string.Empty;
        
        private System.Boolean _IsDing=false;
        
        private System.Boolean _IsCai=false;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public CommentActiveLogInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 会员ID
        /// </summary>
        public System.Int32 UserID 
        {
            get { return _UserID; }
            set { _UserID = value; }
        }
        
        /// <summary>
        /// 会员名称
        /// </summary>
        public System.String UserName 
        {
            get { return _UserName; }
            set { _UserName = value; }
        }
        
        /// <summary>
        /// 内容ID
        /// </summary>
        public System.Int32 ContentID 
        {
            get { return _ContentID; }
            set { _ContentID = value; }
        }
        
        /// <summary>
        /// 评论ID
        /// </summary>
        public System.Int32 CommentID 
        {
            get { return _CommentID; }
            set { _CommentID = value; }
        }
        
        /// <summary>
        /// IP地址
        /// </summary>
        public System.String IPAddress 
        {
            get { return _IPAddress; }
            set { _IPAddress = value; }
        }
        
        /// <summary>
        /// IP地址所在区域
        /// </summary>
        public System.String IPArea 
        {
            get { return _IPArea; }
            set { _IPArea = value; }
        }
        
        /// <summary>
        /// 是否顶
        /// </summary>
        public System.Boolean IsDing 
        {
            get { return _IsDing; }
            set { _IsDing = value; }
        }
        
        /// <summary>
        /// 是否踩
        /// </summary>
        public System.Boolean IsCai 
        {
            get { return _IsCai; }
            set { _IsCai = value; }
        }
        
        /// <summary>
        /// 语言版本
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 时间
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_CommentActiveLog";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,UserID,UserName,ContentID,CommentID,IPAddress,IPArea,IsDing,IsCai,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("UserID");
                    
                    _listField.Add("UserName");
                    
                    _listField.Add("ContentID");
                    
                    _listField.Add("CommentID");
                    
                    _listField.Add("IPAddress");
                    
                    _listField.Add("IPArea");
                    
                    _listField.Add("IsDing");
                    
                    _listField.Add("IsCai");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}