//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:43
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity
{
    /// <summary>
    /// 
    [Serializable]
    public partial class CompanyInfo : JObject, IEntity
    {
        #region Khai báo

        private System.Int32 _AutoID = 0;

        private System.String _Name = string.Empty;

        private System.String _Address = string.Empty;

        private System.String _Phone = string.Empty;

        private System.Boolean _IsRecommend = false;

        private System.Int32 _Sort = 0;

        private System.DateTime _AutoTimeStamp = new DateTime(1900, 1, 1);

        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 
        /// </summary>
        public CompanyInfo()
        {
            //
        }

        #region Lớp khai báo

        /// <summary>
        /// 
        /// </summary>
        public System.Int32 AutoID
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String Name
        {
            get { return _Name; }
            set { _Name = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String Address
        {
            get { return _Address; }
            set { _Address = value; }
        }

        /// <summary>
        ///
        /// </summary>
        public System.String Phone
        {
            get { return _Phone; }
            set { _Phone = value; }
        }

       
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean IsRecommend
        {
            get { return _IsRecommend; }
            set { _IsRecommend = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32 Sort
        {
            get { return _Sort; }
            set { _Sort = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.DateTime AutoTimeStamp
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "dh_Company";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID, Name, Address, Phone, IsRecommend, Sort, AutoTimeStamp";
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {
                    _listField = new List<System.String>();

                    _listField.Add("AutoID");

                    _listField.Add("Name");

                    _listField.Add("Address");

                    _listField.Add("Phone");

                    _listField.Add("IsRecommend");

                    _listField.Add("Sort");

                    _listField.Add("AutoTimeStamp");

                }

                return _listField;
            }
        }

        #endregion

    }
}