//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-10-29 16:09:18
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 模型实体类
    /// </summary>
    [Serializable]
    public partial class ContModelInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _ModelName=string.Empty;
        
        private System.String _TableName=string.Empty;
        
        private System.String _ModelDesc=string.Empty;
        
        private System.Boolean _IsUsing=false;
        
        private System.String _Creator=string.Empty;
        
        private System.Int32 _Sort=0;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public ContModelInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 模型名称
        /// </summary>
        public System.String ModelName 
        {
            get { return _ModelName; }
            set { _ModelName = value; }
        }
        
        /// <summary>
        /// 表名
        /// </summary>
        public System.String TableName 
        {
            get { return _TableName; }
            set { _TableName = value; }
        }
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String ModelDesc 
        {
            get { return _ModelDesc; }
            set { _ModelDesc = value; }
        }
        
        /// <summary>
        /// 是否启用
        /// </summary>
        public System.Boolean IsUsing 
        {
            get { return _IsUsing; }
            set { _IsUsing = value; }
        }
        
        /// <summary>
        /// 创建者
        /// </summary>
        public System.String Creator 
        {
            get { return _Creator; }
            set { _Creator = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 创建日期
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_ContModel";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,ModelName,TableName,ModelDesc,IsUsing,Creator,Sort,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("ModelName");
                    
                    _listField.Add("TableName");
                    
                    _listField.Add("ModelDesc");
                    
                    _listField.Add("IsUsing");
                    
                    _listField.Add("Creator");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}