//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-12-29 10:55:36
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 内容实体类
    /// </summary>
    [Serializable]
    public partial class ContentInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _NodeID=0;
        
        private System.String _NodeName=string.Empty;
        
        private System.Int32 _ModelID=0;
        
        private System.String _TableName=string.Empty;
        
        private System.String _Title=string.Empty;
        
        private System.String _SubTitle=string.Empty;
        
        private System.String _Summary=string.Empty;
        
        private System.String _Author=string.Empty;
        
        private System.String _Editor=string.Empty;
        
        private System.String _Source=string.Empty;
        
        private System.String _SourceUrl=string.Empty;
        
        private System.String _Content=string.Empty;
        
        private System.String _Attachment=string.Empty;
        
        private System.String _TagKey=string.Empty;
        
        private System.String _ContentImage=string.Empty;
        
        private System.String _RelateContent=string.Empty;
        
        private System.String _SeoKey=string.Empty;
        
        private System.String _SeoDescription=string.Empty;
        
        private System.Int32 _Hit=0;
        
        private System.String _TemplateFile=string.Empty;
        
        private System.Int32 _CustomRecommend=0;
        
        private System.Boolean _IsTop=false;
        
        private System.Boolean _IsRecommend=false;
        
        private System.Boolean _IsNew=false;
        
        private System.String _Lang=string.Empty;
        
        private System.String _Inputer=string.Empty;
        
        private System.Int32 _Sort=0;
        
        private System.Int32 _Status=0;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public ContentInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 栏目ID
        /// </summary>
        public System.Int32 NodeID 
        {
            get { return _NodeID; }
            set { _NodeID = value; }
        }
        
        /// <summary>
        /// 栏目名称
        /// </summary>
        public System.String NodeName 
        {
            get { return _NodeName; }
            set { _NodeName = value; }
        }
        
        /// <summary>
        /// 模型ID
        /// </summary>
        public System.Int32 ModelID 
        {
            get { return _ModelID; }
            set { _ModelID = value; }
        }
        
        /// <summary>
        /// 自定义表名
        /// </summary>
        public System.String TableName 
        {
            get { return _TableName; }
            set { _TableName = value; }
        }
        
        /// <summary>
        /// 标题
        /// </summary>
        public System.String Title 
        {
            get { return _Title; }
            set { _Title = value; }
        }
        
        /// <summary>
        /// 副标题
        /// </summary>
        public System.String SubTitle 
        {
            get { return _SubTitle; }
            set { _SubTitle = value; }
        }
        
        /// <summary>
        /// 摘要
        /// </summary>
        public System.String Summary 
        {
            get { return _Summary; }
            set { _Summary = value; }
        }
        
        /// <summary>
        /// 作者
        /// </summary>
        public System.String Author 
        {
            get { return _Author; }
            set { _Author = value; }
        }
        
        /// <summary>
        /// 编辑
        /// </summary>
        public System.String Editor 
        {
            get { return _Editor; }
            set { _Editor = value; }
        }
        
        /// <summary>
        /// 来源
        /// </summary>
        public System.String Source 
        {
            get { return _Source; }
            set { _Source = value; }
        }
        
        /// <summary>
        /// 来源地址
        /// </summary>
        public System.String SourceUrl 
        {
            get { return _SourceUrl; }
            set { _SourceUrl = value; }
        }
        
        /// <summary>
        /// 内容
        /// </summary>
        public System.String Content 
        {
            get { return _Content; }
            set { _Content = value; }
        }
        
        /// <summary>
        /// 附件
        /// </summary>
        public System.String Attachment 
        {
            get { return _Attachment; }
            set { _Attachment = value; }
        }
        
        /// <summary>
        /// 标签集
        /// </summary>
        public System.String TagKey 
        {
            get { return _TagKey; }
            set { _TagKey = value; }
        }
        
        /// <summary>
        /// 图片
        /// </summary>
        public System.String ContentImage 
        {
            get { return _ContentImage; }
            set { _ContentImage = value; }
        }
        
        /// <summary>
        /// 相关内容
        /// </summary>
        public System.String RelateContent 
        {
            get { return _RelateContent; }
            set { _RelateContent = value; }
        }
        
        /// <summary>
        /// SEO关键字
        /// </summary>
        public System.String SeoKey 
        {
            get { return _SeoKey; }
            set { _SeoKey = value; }
        }
        
        /// <summary>
        /// SEO描述
        /// </summary>
        public System.String SeoDescription 
        {
            get { return _SeoDescription; }
            set { _SeoDescription = value; }
        }
        
        /// <summary>
        /// 点击数
        /// </summary>
        public System.Int32 Hit 
        {
            get { return _Hit; }
            set { _Hit = value; }
        }
        
        /// <summary>
        /// 模板文件
        /// </summary>
        public System.String TemplateFile 
        {
            get { return _TemplateFile; }
            set { _TemplateFile = value; }
        }
        
        /// <summary>
        /// 用户推荐度
        /// </summary>
        public System.Int32 CustomRecommend 
        {
            get { return _CustomRecommend; }
            set { _CustomRecommend = value; }
        }
        
        /// <summary>
        /// 置顶
        /// </summary>
        public System.Boolean IsTop 
        {
            get { return _IsTop; }
            set { _IsTop = value; }
        }
        
        /// <summary>
        /// 推荐
        /// </summary>
        public System.Boolean IsRecommend 
        {
            get { return _IsRecommend; }
            set { _IsRecommend = value; }
        }
        
        /// <summary>
        /// 最新
        /// </summary>
        public System.Boolean IsNew 
        {
            get { return _IsNew; }
            set { _IsNew = value; }
        }
        
        /// <summary>
        /// 语言版本
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 录入者
        /// </summary>
        public System.String Inputer 
        {
            get { return _Inputer; }
            set { _Inputer = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 状态
        /// </summary>
        public System.Int32 Status 
        {
            get { return _Status; }
            set { _Status = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_Content";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,NodeID,NodeName,ModelID,TableName,Title,SubTitle,Summary,Author,Editor,Source,SourceUrl,Content,Attachment,TagKey,ContentImage,RelateContent,SeoKey,SeoDescription,Hit,TemplateFile,CustomRecommend,IsTop,IsRecommend,IsNew,Lang,Inputer,Sort,Status,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("NodeID");
                    
                    _listField.Add("NodeName");
                    
                    _listField.Add("ModelID");
                    
                    _listField.Add("TableName");
                    
                    _listField.Add("Title");
                    
                    _listField.Add("SubTitle");
                    
                    _listField.Add("Summary");
                    
                    _listField.Add("Author");
                    
                    _listField.Add("Editor");
                    
                    _listField.Add("Source");
                    
                    _listField.Add("SourceUrl");
                    
                    _listField.Add("Content");
                    
                    _listField.Add("Attachment");
                    
                    _listField.Add("TagKey");
                    
                    _listField.Add("ContentImage");
                    
                    _listField.Add("RelateContent");
                    
                    _listField.Add("SeoKey");
                    
                    _listField.Add("SeoDescription");
                    
                    _listField.Add("Hit");
                    
                    _listField.Add("TemplateFile");
                    
                    _listField.Add("CustomRecommend");
                    
                    _listField.Add("IsTop");
                    
                    _listField.Add("IsRecommend");
                    
                    _listField.Add("IsNew");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("Inputer");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("Status");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}