//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-10-29 16:08:27
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 内容字段实体类
    /// </summary>
    [Serializable]
    public partial class ContFieldInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _ModelID=0;
        
        private System.String _FieldName=string.Empty;
        
        private System.Int32 _FieldType=0;
        
        private System.String _DataType=string.Empty;
        
        private System.Int32 _DataLength=0;
        
        private System.String _Alias=string.Empty;
        
        private System.String _Tip=string.Empty;
        
        private System.String _FieldDesc=string.Empty;
        
        private System.String _DefaultValue=string.Empty;
        
        private System.String _Setting=string.Empty;
        
        private System.Boolean _EnableNull=false;
        
        private System.Boolean _EnableSearch=false;
        
        private System.Boolean _IsUsing=false;
        
        private System.Boolean _IsSystem=false;
        
        private System.Int32 _Sort=0;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public ContFieldInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 模型ID
        /// </summary>
        public System.Int32 ModelID 
        {
            get { return _ModelID; }
            set { _ModelID = value; }
        }
        
        /// <summary>
        /// 字段名称
        /// </summary>
        public System.String FieldName 
        {
            get { return _FieldName; }
            set { _FieldName = value; }
        }
        
        /// <summary>
        /// 字段类型
        /// </summary>
        public System.Int32 FieldType 
        {
            get { return _FieldType; }
            set { _FieldType = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String DataType 
        {
            get { return _DataType; }
            set { _DataType = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 DataLength 
        {
            get { return _DataLength; }
            set { _DataLength = value; }
        }
        
        /// <summary>
        /// 别名
        /// </summary>
        public System.String Alias 
        {
            get { return _Alias; }
            set { _Alias = value; }
        }
        
        /// <summary>
        /// 提示
        /// </summary>
        public System.String Tip 
        {
            get { return _Tip; }
            set { _Tip = value; }
        }
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String FieldDesc 
        {
            get { return _FieldDesc; }
            set { _FieldDesc = value; }
        }
        
        /// <summary>
        /// 默认值
        /// </summary>
        public System.String DefaultValue 
        {
            get { return _DefaultValue; }
            set { _DefaultValue = value; }
        }
        
        /// <summary>
        /// 设置
        /// </summary>
        public System.String Setting 
        {
            get { return _Setting; }
            set { _Setting = value; }
        }
        
        /// <summary>
        /// 是否允许为空
        /// </summary>
        public System.Boolean EnableNull 
        {
            get { return _EnableNull; }
            set { _EnableNull = value; }
        }
        
        /// <summary>
        /// 是否允许搜索
        /// </summary>
        public System.Boolean EnableSearch 
        {
            get { return _EnableSearch; }
            set { _EnableSearch = value; }
        }
        
        /// <summary>
        /// 是否启用
        /// </summary>
        public System.Boolean IsUsing 
        {
            get { return _IsUsing; }
            set { _IsUsing = value; }
        }
        
        /// <summary>
        /// 是否系统自有
        /// </summary>
        public System.Boolean IsSystem 
        {
            get { return _IsSystem; }
            set { _IsSystem = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_ContField";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,ModelID,FieldName,FieldType,DataType,DataLength,Alias,Tip,FieldDesc,DefaultValue,Setting,EnableNull,EnableSearch,IsUsing,IsSystem,Sort,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("ModelID");
                    
                    _listField.Add("FieldName");
                    
                    _listField.Add("FieldType");
                    
                    _listField.Add("DataType");
                    
                    _listField.Add("DataLength");
                    
                    _listField.Add("Alias");
                    
                    _listField.Add("Tip");
                    
                    _listField.Add("FieldDesc");
                    
                    _listField.Add("DefaultValue");
                    
                    _listField.Add("Setting");
                    
                    _listField.Add("EnableNull");
                    
                    _listField.Add("EnableSearch");
                    
                    _listField.Add("IsUsing");
                    
                    _listField.Add("IsSystem");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}