//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2016-3-30 11:26:42
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 优惠券实体类
    /// </summary>
    [Serializable]
    public partial class CouponsInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _Title=string.Empty;
        
        private System.String _SN=string.Empty;
        
        private System.Decimal _Notes=0.0m;
        
        private System.Decimal _Touch=0.0m;
        
        private System.DateTime _StartTime=new DateTime(1900, 1, 1);
        
        private System.DateTime _EndTime=new DateTime(1900, 1, 1);
        
        private System.String _UserName=string.Empty;
        
        private System.Boolean _IsUsed=false;
        
        private System.Int32 _Sort=0;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public CouponsInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String Title 
        {
            get { return _Title; }
            set { _Title = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String SN 
        {
            get { return _SN; }
            set { _SN = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Decimal Notes 
        {
            get { return _Notes; }
            set { _Notes = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Decimal Touch 
        {
            get { return _Touch; }
            set { _Touch = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime StartTime 
        {
            get { return _StartTime; }
            set { _StartTime = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime EndTime 
        {
            get { return _EndTime; }
            set { _EndTime = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String UserName 
        {
            get { return _UserName; }
            set { _UserName = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean IsUsed 
        {
            get { return _IsUsed; }
            set { _IsUsed = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_Coupons";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,Title,SN,Notes,Touch,StartTime,EndTime,UserName,IsUsed,Sort,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("Title");
                    
                    _listField.Add("SN");
                    
                    _listField.Add("Notes");
                    
                    _listField.Add("Touch");
                    
                    _listField.Add("StartTime");
                    
                    _listField.Add("EndTime");
                    
                    _listField.Add("UserName");
                    
                    _listField.Add("IsUsed");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}