//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:20
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 实体类
    /// </summary>
    [Serializable]
    public partial class CreateFileInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _Title=string.Empty;
        
        private System.String _TemplateFile=string.Empty;
        
        private System.String _FilePath=string.Empty;
        
        private System.String _FileName=string.Empty;
        
        private System.String _Dicts=string.Empty;
        
        private System.String _CountSQL=string.Empty;
        
        private System.Int32 _RecordCount=0;
        
        private System.Int32 _PageSize=0;
        
        private System.Boolean _IsPage=false;
        
        private System.Boolean _IsCreated=false;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public CreateFileInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String Title 
        {
            get { return _Title; }
            set { _Title = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String TemplateFile 
        {
            get { return _TemplateFile; }
            set { _TemplateFile = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String FilePath 
        {
            get { return _FilePath; }
            set { _FilePath = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String FileName 
        {
            get { return _FileName; }
            set { _FileName = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String Dicts 
        {
            get { return _Dicts; }
            set { _Dicts = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String CountSQL 
        {
            get { return _CountSQL; }
            set { _CountSQL = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 RecordCount 
        {
            get { return _RecordCount; }
            set { _RecordCount = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 PageSize 
        {
            get { return _PageSize; }
            set { _PageSize = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean IsPage 
        {
            get { return _IsPage; }
            set { _IsPage = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean IsCreated 
        {
            get { return _IsCreated; }
            set { _IsCreated = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_CreateFile";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,Title,TemplateFile,FilePath,FileName,Dicts,CountSQL,RecordCount,PageSize,IsPage,IsCreated,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("Title");
                    
                    _listField.Add("TemplateFile");
                    
                    _listField.Add("FilePath");
                    
                    _listField.Add("FileName");
                    
                    _listField.Add("Dicts");
                    
                    _listField.Add("CountSQL");
                    
                    _listField.Add("RecordCount");
                    
                    _listField.Add("PageSize");
                    
                    _listField.Add("IsPage");
                    
                    _listField.Add("IsCreated");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}