//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:43
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity
{
    /// <summary>
    /// 
    [Serializable]
    public partial class CustomerInfo : JObject, IEntity
    {
        #region Khai báo

        private System.Int32 _AutoID = 0;

        private System.String _PortName = string.Empty;

        private System.String _PortCode = string.Empty;

        public System.String PortCode
        {
            get { return _PortCode; }
            set { _PortCode = value; }
        }

        private System.String _EnglishName = string.Empty;

        public System.String EnglishName
        {
            get { return _EnglishName; }
            set { _EnglishName = value; }
        }

        private System.String _BussinessStatus = string.Empty;

        public System.String BussinessStatus
        {
            get { return _BussinessStatus; }
            set { _BussinessStatus = value; }
        }

        private System.String _Under = string.Empty;

        public System.String Under
        {
            get { return _Under; }
            set { _Under = value; }
        }

        private System.String _PortLocationX = string.Empty;

        public System.String PortLocationX
        {
            get { return _PortLocationX; }
            set { _PortLocationX = value; }
        }
        private System.String _PortLocationY = string.Empty;

        public System.String PortLocationY
        {
            get { return _PortLocationY; }
            set { _PortLocationY = value; }
        }
        private System.String _PilotLocation = string.Empty;

        public System.String PilotLocation
        {
            get { return _PilotLocation; }
            set { _PilotLocation = value; }
        }
        private System.String _Address = string.Empty;

        public System.String Address
        {
            get { return _Address; }
            set { _Address = value; }
        }
        private System.String _Phone = string.Empty;

        public System.String Phone
        {
            get { return _Phone; }
            set { _Phone = value; }
        }
        private System.String _Email = string.Empty;

        public System.String Email
        {
            get { return _Email; }
            set { _Email = value; }
        }
        private System.String _Website = string.Empty;

        public System.String Website
        {
            get { return _Website; }
            set { _Website = value; }
        }
        private System.String _TotalLength = string.Empty;

        public System.String TotalLength
        {
            get { return _TotalLength; }
            set { _TotalLength = value; }
        }
        private System.String _TidalRegime = string.Empty;

        public System.String TidalRegime
        {
            get { return _TidalRegime; }
            set { _TidalRegime = value; }
        }
        private System.String _AverageVariation = string.Empty;

        public System.String AverageVariation
        {
            get { return _AverageVariation; }
            set { _AverageVariation = value; }
        }
        private System.String _MaximumDraft = string.Empty;

        public System.String MaximumDraft
        {
            get { return _MaximumDraft; }
            set { _MaximumDraft = value; }
        }
        private System.String _MaximumSize = string.Empty;

        public System.String MaximumSize
        {
            get { return _MaximumSize; }
            set { _MaximumSize = value; }
        }
        private System.String _TotalPortArea = string.Empty;

        public System.String TotalPortArea
        {
            get { return _TotalPortArea; }
            set { _TotalPortArea = value; }
        }
        private System.String _TotalWarehousingArea = string.Empty;

        public System.String TotalWarehousingArea
        {
            get { return _TotalWarehousingArea; }
            set { _TotalWarehousingArea = value; }
        }
        private System.String _Warehouses = string.Empty;

        public System.String Warehouses
        {
            get { return _Warehouses; }
            set { _Warehouses = value; }
        }
        private System.String _Tank = string.Empty;

        public System.String Tank
        {
            get { return _Tank; }
            set { _Tank = value; }
        }
        private System.String _CargoThroughput = string.Empty;

        public System.String CargoThroughput
        {
            get { return _CargoThroughput; }
            set { _CargoThroughput = value; }
        }

        private System.Boolean _IsRecommend = false;

        private System.Int32 _Sort = 0;

        private System.DateTime _AutoTimeStamp = new DateTime(1900, 1, 1);

        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 
        /// </summary>
        public CustomerInfo()
        {
            //
        }

        #region Lớp khai báo

        /// <summary>
        /// 
        /// </summary>
        public System.Int32 AutoID
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String PortName
        {
            get { return _PortName; }
            set { _PortName = value; }
        }


        /// <summary>
        /// 
        /// </summary>
        public System.Boolean IsRecommend
        {
            get { return _IsRecommend; }
            set { _IsRecommend = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32 Sort
        {
            get { return _Sort; }
            set { _Sort = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.DateTime AutoTimeStamp
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "dh_Company";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID, PortName, PortCode, EnglishName, BussinessStatus, Under, PortLocationX, PortLocationY, PilotLocation, Address, Phone, Email, Website, TotalLength, TidalRegime, AverageVariation, " +
                         "MaximumDraft, MaximumSize, TotalPortArea, TotalWarehousingArea, Warehouses, Tank, CargoThroughput,IsRecommend,Sort, AutoTimeStamp";
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {
                    _listField = new List<System.String>();

                    _listField.Add("AutoID");

                    _listField.Add("PortName");
                    _listField.Add("PortCode");
                    _listField.Add("EnglishName");
                    _listField.Add("BussinessStatus");
                    _listField.Add("Under");
                    _listField.Add("PortLocationX");
                    _listField.Add("PortLocationY");
                    _listField.Add("PilotLocation");
                    _listField.Add("Address");
                    _listField.Add("Phone");
                    _listField.Add("Email");
                    _listField.Add("Website");
                    _listField.Add("TotalLength");
                    _listField.Add("TidalRegime");
                    _listField.Add("AverageVariation");
                    _listField.Add("MaximumDraft");
                    _listField.Add("MaximumSize");
                    _listField.Add("TotalPortArea");
                    _listField.Add("TotalWarehousingArea");
                    _listField.Add("Warehouses");
                    _listField.Add("Tank");
                    _listField.Add("CargoThroughput");
                    _listField.Add("IsRecommend");
                    _listField.Add("Sort");

                    _listField.Add("AutoTimeStamp");

                }

                return _listField;
            }
        }

        #endregion

    }
}