//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2016-5-18 11:10:47
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 发货记录实体类
    /// </summary>
    [Serializable]
    public partial class DeliveryRecInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _OrderNo=string.Empty;
        
        private System.String _ProductName=string.Empty;
        
        private System.String _ShippingType=string.Empty;
        
        private System.String _KuaidiCom=string.Empty;
        
        private System.String _ShippingNo=string.Empty;
        
        private System.Decimal _ShippingFee=0.0m;
        
        private System.String _Sender=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public DeliveryRecInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 订单编号
        /// </summary>
        public System.String OrderNo 
        {
            get { return _OrderNo; }
            set { _OrderNo = value; }
        }
        
        /// <summary>
        /// 商品名称
        /// </summary>
        public System.String ProductName 
        {
            get { return _ProductName; }
            set { _ProductName = value; }
        }
        
        /// <summary>
        /// 货运方式
        /// </summary>
        public System.String ShippingType 
        {
            get { return _ShippingType; }
            set { _ShippingType = value; }
        }
        
        /// <summary>
        /// 货运公司
        /// </summary>
        public System.String KuaidiCom 
        {
            get { return _KuaidiCom; }
            set { _KuaidiCom = value; }
        }
        
        /// <summary>
        /// 快递单号
        /// </summary>
        public System.String ShippingNo 
        {
            get { return _ShippingNo; }
            set { _ShippingNo = value; }
        }
        
        /// <summary>
        /// 货运费用
        /// </summary>
        public System.Decimal ShippingFee 
        {
            get { return _ShippingFee; }
            set { _ShippingFee = value; }
        }
        
        /// <summary>
        /// 发货人
        /// </summary>
        public System.String Sender 
        {
            get { return _Sender; }
            set { _Sender = value; }
        }
        
        /// <summary>
        /// 发货时间
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_DeliveryRec";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,OrderNo,ProductName,ShippingType,KuaidiCom,ShippingNo,ShippingFee,Sender,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("OrderNo");
                    
                    _listField.Add("ProductName");
                    
                    _listField.Add("ShippingType");
                    
                    _listField.Add("KuaidiCom");
                    
                    _listField.Add("ShippingNo");
                    
                    _listField.Add("ShippingFee");
                    
                    _listField.Add("Sender");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}