//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:52:07
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 字典内容实体类
    /// </summary>
    [Serializable]
    public partial class DictItemInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _DictID=0;
        
        private System.Int32 _ParentID=0;
        
        private System.String _KeyName=string.Empty;
        
        private System.String _KeyValue=string.Empty;
        
        private System.Int32 _Sort=0;
        
        private System.Boolean _IsUsing=false;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public DictItemInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 字典ID
        /// </summary>
        public System.Int32 DictID 
        {
            get { return _DictID; }
            set { _DictID = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 ParentID 
        {
            get { return _ParentID; }
            set { _ParentID = value; }
        }
        
        /// <summary>
        /// 键名称
        /// </summary>
        public System.String KeyName 
        {
            get { return _KeyName; }
            set { _KeyName = value; }
        }
        
        /// <summary>
        /// 键值
        /// </summary>
        public System.String KeyValue 
        {
            get { return _KeyValue; }
            set { _KeyValue = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean IsUsing 
        {
            get { return _IsUsing; }
            set { _IsUsing = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "sys_DictItem";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,DictID,ParentID,KeyName,KeyValue,Sort,IsUsing,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("DictID");
                    
                    _listField.Add("ParentID");
                    
                    _listField.Add("KeyName");
                    
                    _listField.Add("KeyValue");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("IsUsing");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}