//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2016-3-30 18:07:53
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 商品收藏实体类
    /// </summary>
    [Serializable]
    public partial class FavoritesInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _UserID=0;
        
        private System.Int32 _ProductID=0;
        
        private System.String _ProductName=string.Empty;
        
        private System.String _ProductImage=string.Empty;
        
        private System.Decimal _Price=0.0m;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public FavoritesInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 UserID 
        {
            get { return _UserID; }
            set { _UserID = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 ProductID 
        {
            get { return _ProductID; }
            set { _ProductID = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String ProductName 
        {
            get { return _ProductName; }
            set { _ProductName = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String ProductImage 
        {
            get { return _ProductImage; }
            set { _ProductImage = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Decimal Price 
        {
            get { return _Price; }
            set { _Price = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_Favorites";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,UserID,ProductID,ProductName,ProductImage,Price,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("UserID");
                    
                    _listField.Add("ProductID");
                    
                    _listField.Add("ProductName");
                    
                    _listField.Add("ProductImage");
                    
                    _listField.Add("Price");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}