//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2015-7-20 15:09:45
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 文件上传表实体类
    /// </summary>
    [Serializable]
    public partial class FileUploadInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _FolderID=0;
        
        private System.String _FileName=string.Empty;
        
        private System.String _FileExt=string.Empty;
        
        private System.Int32 _FileSize=0;
        
        private System.String _VirtualPath=string.Empty;
        
        private System.String _Thumb=string.Empty;
        
        private System.String _OriginalPath=string.Empty;
        
        private System.String _UserType=string.Empty;
        
        private System.String _UserName=string.Empty;
        
        private System.Int32 _DownloadCount=0;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public FileUploadInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 FolderID 
        {
            get { return _FolderID; }
            set { _FolderID = value; }
        }
        
        /// <summary>
        /// 文件名称
        /// </summary>
        public System.String FileName 
        {
            get { return _FileName; }
            set { _FileName = value; }
        }
        
        /// <summary>
        /// 扩展名
        /// </summary>
        public System.String FileExt 
        {
            get { return _FileExt; }
            set { _FileExt = value; }
        }
        
        /// <summary>
        /// 文件大小
        /// </summary>
        public System.Int32 FileSize 
        {
            get { return _FileSize; }
            set { _FileSize = value; }
        }
        
        /// <summary>
        /// 虚拟路径
        /// </summary>
        public System.String VirtualPath 
        {
            get { return _VirtualPath; }
            set { _VirtualPath = value; }
        }
        
        /// <summary>
        /// 缩略图
        /// </summary>
        public System.String Thumb 
        {
            get { return _Thumb; }
            set { _Thumb = value; }
        }
        
        /// <summary>
        /// 文件原路径
        /// </summary>
        public System.String OriginalPath 
        {
            get { return _OriginalPath; }
            set { _OriginalPath = value; }
        }
        
        /// <summary>
        /// 上传者类型
        /// </summary>
        public System.String UserType 
        {
            get { return _UserType; }
            set { _UserType = value; }
        }
        
        /// <summary>
        /// 上传者名称
        /// </summary>
        public System.String UserName 
        {
            get { return _UserName; }
            set { _UserName = value; }
        }
        
        /// <summary>
        /// 下载次数
        /// </summary>
        public System.Int32 DownloadCount 
        {
            get { return _DownloadCount; }
            set { _DownloadCount = value; }
        }
        
        /// <summary>
        /// 语言版本
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "sys_FileUpload";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,FolderID,FileName,FileExt,FileSize,VirtualPath,Thumb,OriginalPath,UserType,UserName,DownloadCount,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("FolderID");
                    
                    _listField.Add("FileName");
                    
                    _listField.Add("FileExt");
                    
                    _listField.Add("FileSize");
                    
                    _listField.Add("VirtualPath");
                    
                    _listField.Add("Thumb");
                    
                    _listField.Add("OriginalPath");
                    
                    _listField.Add("UserType");
                    
                    _listField.Add("UserName");
                    
                    _listField.Add("DownloadCount");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}