//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2015-9-23 11:12:20
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 文件夹管理实体类
    /// </summary>
    [Serializable]
    public partial class FolderInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _FolderName=string.Empty;
        
        private System.Int32 _ParentID=0;
        
        private System.Int32 _RootID=0;
        
        private System.Int32 _Depth=0;
        
        private System.Int32 _ChildCount=0;
        
        private System.String _ChildList=string.Empty;
        
        private System.String _Remark=string.Empty;
        
        private System.Int32 _Sort=0;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public FolderInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 文件夹名称
        /// </summary>
        public System.String FolderName 
        {
            get { return _FolderName; }
            set { _FolderName = value; }
        }
        
        /// <summary>
        /// 上级文件夹ID
        /// </summary>
        public System.Int32 ParentID 
        {
            get { return _ParentID; }
            set { _ParentID = value; }
        }
        
        /// <summary>
        /// 根文件夹ID
        /// </summary>
        public System.Int32 RootID 
        {
            get { return _RootID; }
            set { _RootID = value; }
        }
        
        /// <summary>
        /// 层级
        /// </summary>
        public System.Int32 Depth 
        {
            get { return _Depth; }
            set { _Depth = value; }
        }
        
        /// <summary>
        /// 下级目录数量
        /// </summary>
        public System.Int32 ChildCount 
        {
            get { return _ChildCount; }
            set { _ChildCount = value; }
        }
        
        /// <summary>
        /// 下级目录列表
        /// </summary>
        public System.String ChildList 
        {
            get { return _ChildList; }
            set { _ChildList = value; }
        }
        
        /// <summary>
        /// 备注
        /// </summary>
        public System.String Remark 
        {
            get { return _Remark; }
            set { _Remark = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 语种
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 时间
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "sys_Folder";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,FolderName,ParentID,RootID,Depth,ChildCount,ChildList,Remark,Sort,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("FolderName");
                    
                    _listField.Add("ParentID");
                    
                    _listField.Add("RootID");
                    
                    _listField.Add("Depth");
                    
                    _listField.Add("ChildCount");
                    
                    _listField.Add("ChildList");
                    
                    _listField.Add("Remark");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}