//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2015-9-22 11:58:15
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 库存属性实体类
    /// </summary>
    [Serializable]
    public partial class GoodsAttrInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _AttrName=string.Empty;
        
        private System.String _AttrValue=string.Empty;
        
        private System.Int32 _ParentID=0;
        
        private System.String _AttrPath=string.Empty;
        
        private System.Int32 _Depth=0;
        
        private System.Int32 _ProID=0;
        
        private System.String _PreviewImg=string.Empty;
        
        private System.Int32 _ChildCount=0;
        
        private System.Decimal _Price=0.0m;
        
        private System.Int32 _Quantity=0;
        
        private System.Int32 _Sort=0;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public GoodsAttrInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 属性名称
        /// </summary>
        public System.String AttrName 
        {
            get { return _AttrName; }
            set { _AttrName = value; }
        }
        
        /// <summary>
        /// 属性值
        /// </summary>
        public System.String AttrValue 
        {
            get { return _AttrValue; }
            set { _AttrValue = value; }
        }
        
        /// <summary>
        /// 上级属性
        /// </summary>
        public System.Int32 ParentID 
        {
            get { return _ParentID; }
            set { _ParentID = value; }
        }
        
        /// <summary>
        /// 属性路径
        /// </summary>
        public System.String AttrPath 
        {
            get { return _AttrPath; }
            set { _AttrPath = value; }
        }
        
        /// <summary>
        /// 层级
        /// </summary>
        public System.Int32 Depth 
        {
            get { return _Depth; }
            set { _Depth = value; }
        }
        
        /// <summary>
        /// 商品ID
        /// </summary>
        public System.Int32 ProID 
        {
            get { return _ProID; }
            set { _ProID = value; }
        }
        
        /// <summary>
        /// 预览图片
        /// </summary>
        public System.String PreviewImg 
        {
            get { return _PreviewImg; }
            set { _PreviewImg = value; }
        }
        
        /// <summary>
        /// 下级属性数量
        /// </summary>
        public System.Int32 ChildCount 
        {
            get { return _ChildCount; }
            set { _ChildCount = value; }
        }
        
        /// <summary>
        /// 价格
        /// </summary>
        public System.Decimal Price 
        {
            get { return _Price; }
            set { _Price = value; }
        }
        
        /// <summary>
        /// 数量
        /// </summary>
        public System.Int32 Quantity 
        {
            get { return _Quantity; }
            set { _Quantity = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 语种
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_GoodsAttr";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,AttrName,AttrValue,ParentID,AttrPath,Depth,ProID,PreviewImg,ChildCount,Price,Quantity,Sort,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("AttrName");
                    
                    _listField.Add("AttrValue");
                    
                    _listField.Add("ParentID");
                    
                    _listField.Add("AttrPath");
                    
                    _listField.Add("Depth");
                    
                    _listField.Add("ProID");
                    
                    _listField.Add("PreviewImg");
                    
                    _listField.Add("ChildCount");
                    
                    _listField.Add("Price");
                    
                    _listField.Add("Quantity");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}