//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:23
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 友情链接实体类
    /// </summary>
    [Serializable]
    public partial class LinksInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _LinkName=string.Empty;
        
        private System.String _LinkUrl=string.Empty;
        
        private System.String _LinkType=string.Empty;
        
        private System.String _LinkText=string.Empty;
        
        private System.String _LinkImage=string.Empty;
        
        private System.String _LInkFlash=string.Empty;
        
        private System.Boolean _IsAudit=false;
        
        private System.Int32 _Sort=0;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public LinksInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 链接名称
        /// </summary>
        public System.String LinkName 
        {
            get { return _LinkName; }
            set { _LinkName = value; }
        }
        
        /// <summary>
        /// 链接地址
        /// </summary>
        public System.String LinkUrl 
        {
            get { return _LinkUrl; }
            set { _LinkUrl = value; }
        }
        
        /// <summary>
        /// 链接类型
        /// </summary>
        public System.String LinkType 
        {
            get { return _LinkType; }
            set { _LinkType = value; }
        }
        
        /// <summary>
        /// 链接文本
        /// </summary>
        public System.String LinkText 
        {
            get { return _LinkText; }
            set { _LinkText = value; }
        }
        
        /// <summary>
        /// 链接图片
        /// </summary>
        public System.String LinkImage 
        {
            get { return _LinkImage; }
            set { _LinkImage = value; }
        }
        
        /// <summary>
        /// 链接Flash
        /// </summary>
        public System.String LInkFlash 
        {
            get { return _LInkFlash; }
            set { _LInkFlash = value; }
        }
        
        /// <summary>
        /// 是否审核
        /// </summary>
        public System.Boolean IsAudit 
        {
            get { return _IsAudit; }
            set { _IsAudit = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 语言版本
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_Links";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,LinkName,LinkUrl,LinkType,LinkText,LinkImage,LInkFlash,IsAudit,Sort,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("LinkName");
                    
                    _listField.Add("LinkUrl");
                    
                    _listField.Add("LinkType");
                    
                    _listField.Add("LinkText");
                    
                    _listField.Add("LinkImage");
                    
                    _listField.Add("LInkFlash");
                    
                    _listField.Add("IsAudit");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}