//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2016-3-31 10:41:21
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 订单操作实体类
    /// </summary>
    [Serializable]
    public partial class OrderActionInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _OrderID=0;
        
        private System.String _Operator=string.Empty;
        
        private System.Int32 _OrderStatus=0;
        
        private System.String _ActionNote=string.Empty;
        
        private System.String _Remark=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public OrderActionInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 订单ID
        /// </summary>
        public System.Int32 OrderID 
        {
            get { return _OrderID; }
            set { _OrderID = value; }
        }
        
        /// <summary>
        /// 操作者
        /// </summary>
        public System.String Operator 
        {
            get { return _Operator; }
            set { _Operator = value; }
        }
        
        /// <summary>
        /// 订单状态
        /// </summary>
        public System.Int32 OrderStatus 
        {
            get { return _OrderStatus; }
            set { _OrderStatus = value; }
        }
        
        /// <summary>
        /// 详情
        /// </summary>
        public System.String ActionNote 
        {
            get { return _ActionNote; }
            set { _ActionNote = value; }
        }
        
        /// <summary>
        /// 备注
        /// </summary>
        public System.String Remark 
        {
            get { return _Remark; }
            set { _Remark = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_OrderAction";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,OrderID,Operator,OrderStatus,ActionNote,Remark,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("OrderID");
                    
                    _listField.Add("Operator");
                    
                    _listField.Add("OrderStatus");
                    
                    _listField.Add("ActionNote");
                    
                    _listField.Add("Remark");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}