//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2016-4-1 15:28:16
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 订单实体类
    /// </summary>
    [Serializable]
    public partial class OrdersInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _OrderNo=string.Empty;
        
        private System.Int32 _OrderType=0;
        
        private System.Int32 _UserID=0;
        
        private System.String _UserName=string.Empty;
        
        private System.String _AddOrderMethod=string.Empty;
        
        private System.Int32 _CouponsID=0;
        
        private System.Decimal _CouponsValue=0.0m;
        
        private System.Decimal _GoodsTotalAmout=0.0m;
        
        private System.Decimal _OrderShippingFee=0.0m;
        
        private System.Decimal _InsuranceFee=0.0m;
        
        private System.Decimal _OtherFee=0.0m;
        
        private System.Decimal _OrderTotalAmount=0.0m;
        
        private System.String _Consignee=string.Empty;
        
        private System.String _Country=string.Empty;
        
        private System.String _Province=string.Empty;
        
        private System.String _City=string.Empty;
        
        private System.String _County=string.Empty;
        
        private System.String _Address=string.Empty;
        
        private System.String _PostCode=string.Empty;
        
        private System.String _Phone=string.Empty;
        
        private System.String _Mobile=string.Empty;
        
        private System.Int32 _ShippingID=0;
        
        private System.String _ShippingName=string.Empty;
        
        private System.String _ShippingNo=string.Empty;
        
        private System.Int32 _PayID=0;
        
        private System.String _PayName=string.Empty;
        
        private System.String _TradeNo=string.Empty;
        
        private System.Boolean _SendGoodsNeedNotice=false;
        
        private System.Boolean _NeedInvoice=false;
        
        private System.String _InvoiceTitle=string.Empty;
        
        private System.String _InvoiceContent=string.Empty;
        
        private System.Boolean _Invoiced=false;
        
        private System.Boolean _RecInvoice=false;
        
        private System.Int32 _Integral=0;
        
        private System.String _CustomerMsg=string.Empty;
        
        private System.String _Remark=string.Empty;
        
        private System.Int32 _OrderStatus=0;
        
        private System.DateTime _OrderAddTime=new DateTime(1900, 1, 1);
        
        private System.DateTime _OrderAuditTime=new DateTime(1900, 1, 1);
        
        private System.DateTime _OrderPayTime=new DateTime(1900, 1, 1);
        
        private System.DateTime _GoodsSendTime=new DateTime(1900, 1, 1);
        
        private System.DateTime _GoodsServedTime=new DateTime(1900, 1, 1);
        
        private System.DateTime _OrderFinishTime=new DateTime(1900, 1, 1);
        
        private System.DateTime _LastModifyTime=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public OrdersInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 订单流水号
        /// </summary>
        public System.String OrderNo 
        {
            get { return _OrderNo; }
            set { _OrderNo = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 OrderType 
        {
            get { return _OrderType; }
            set { _OrderType = value; }
        }
        
        /// <summary>
        /// 会员ID
        /// </summary>
        public System.Int32 UserID 
        {
            get { return _UserID; }
            set { _UserID = value; }
        }
        
        /// <summary>
        /// 会员名称
        /// </summary>
        public System.String UserName 
        {
            get { return _UserName; }
            set { _UserName = value; }
        }
        
        /// <summary>
        /// 订单添加方式
        /// </summary>
        public System.String AddOrderMethod 
        {
            get { return _AddOrderMethod; }
            set { _AddOrderMethod = value; }
        }
        
        /// <summary>
        /// 优惠券ID
        /// </summary>
        public System.Int32 CouponsID 
        {
            get { return _CouponsID; }
            set { _CouponsID = value; }
        }
        
        /// <summary>
        /// 优惠券面值
        /// </summary>
        public System.Decimal CouponsValue 
        {
            get { return _CouponsValue; }
            set { _CouponsValue = value; }
        }
        
        /// <summary>
        /// 商品总金额
        /// </summary>
        public System.Decimal GoodsTotalAmout 
        {
            get { return _GoodsTotalAmout; }
            set { _GoodsTotalAmout = value; }
        }
        
        /// <summary>
        /// 货运运费
        /// </summary>
        public System.Decimal OrderShippingFee 
        {
            get { return _OrderShippingFee; }
            set { _OrderShippingFee = value; }
        }
        
        /// <summary>
        /// 保险费用
        /// </summary>
        public System.Decimal InsuranceFee 
        {
            get { return _InsuranceFee; }
            set { _InsuranceFee = value; }
        }
        
        /// <summary>
        /// 其它费用
        /// </summary>
        public System.Decimal OtherFee 
        {
            get { return _OtherFee; }
            set { _OtherFee = value; }
        }
        
        /// <summary>
        /// 订单总金额
        /// </summary>
        public System.Decimal OrderTotalAmount 
        {
            get { return _OrderTotalAmount; }
            set { _OrderTotalAmount = value; }
        }
        
        /// <summary>
        /// 收件人
        /// </summary>
        public System.String Consignee 
        {
            get { return _Consignee; }
            set { _Consignee = value; }
        }
        
        /// <summary>
        /// 国家
        /// </summary>
        public System.String Country 
        {
            get { return _Country; }
            set { _Country = value; }
        }
        
        /// <summary>
        /// 省份
        /// </summary>
        public System.String Province 
        {
            get { return _Province; }
            set { _Province = value; }
        }
        
        /// <summary>
        /// 城市
        /// </summary>
        public System.String City 
        {
            get { return _City; }
            set { _City = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String County 
        {
            get { return _County; }
            set { _County = value; }
        }
        
        /// <summary>
        /// 详情地址
        /// </summary>
        public System.String Address 
        {
            get { return _Address; }
            set { _Address = value; }
        }
        
        /// <summary>
        /// 邮编
        /// </summary>
        public System.String PostCode 
        {
            get { return _PostCode; }
            set { _PostCode = value; }
        }
        
        /// <summary>
        /// 电话
        /// </summary>
        public System.String Phone 
        {
            get { return _Phone; }
            set { _Phone = value; }
        }
        
        /// <summary>
        /// 手机
        /// </summary>
        public System.String Mobile 
        {
            get { return _Mobile; }
            set { _Mobile = value; }
        }
        
        /// <summary>
        /// 货运ID
        /// </summary>
        public System.Int32 ShippingID 
        {
            get { return _ShippingID; }
            set { _ShippingID = value; }
        }
        
        /// <summary>
        /// 货运公司名称
        /// </summary>
        public System.String ShippingName 
        {
            get { return _ShippingName; }
            set { _ShippingName = value; }
        }
        
        /// <summary>
        /// 货运单号
        /// </summary>
        public System.String ShippingNo 
        {
            get { return _ShippingNo; }
            set { _ShippingNo = value; }
        }
        
        /// <summary>
        /// 支付方式ID
        /// </summary>
        public System.Int32 PayID 
        {
            get { return _PayID; }
            set { _PayID = value; }
        }
        
        /// <summary>
        /// 支付方式名称
        /// </summary>
        public System.String PayName 
        {
            get { return _PayName; }
            set { _PayName = value; }
        }
        
        /// <summary>
        /// 支付交易编号（支付宝发货的依据）
        /// </summary>
        public System.String TradeNo 
        {
            get { return _TradeNo; }
            set { _TradeNo = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean SendGoodsNeedNotice 
        {
            get { return _SendGoodsNeedNotice; }
            set { _SendGoodsNeedNotice = value; }
        }
        
        /// <summary>
        /// 是否需要发票
        /// </summary>
        public System.Boolean NeedInvoice 
        {
            get { return _NeedInvoice; }
            set { _NeedInvoice = value; }
        }
        
        /// <summary>
        /// 发票开头
        /// </summary>
        public System.String InvoiceTitle 
        {
            get { return _InvoiceTitle; }
            set { _InvoiceTitle = value; }
        }
        
        /// <summary>
        /// 发票内容
        /// </summary>
        public System.String InvoiceContent 
        {
            get { return _InvoiceContent; }
            set { _InvoiceContent = value; }
        }
        
        /// <summary>
        /// 是否已开发票
        /// </summary>
        public System.Boolean Invoiced 
        {
            get { return _Invoiced; }
            set { _Invoiced = value; }
        }
        
        /// <summary>
        /// 是否已发发票
        /// </summary>
        public System.Boolean RecInvoice 
        {
            get { return _RecInvoice; }
            set { _RecInvoice = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 Integral 
        {
            get { return _Integral; }
            set { _Integral = value; }
        }
        
        /// <summary>
        /// 客户留言
        /// </summary>
        public System.String CustomerMsg 
        {
            get { return _CustomerMsg; }
            set { _CustomerMsg = value; }
        }
        
        /// <summary>
        /// 备注
        /// </summary>
        public System.String Remark 
        {
            get { return _Remark; }
            set { _Remark = value; }
        }
        
        /// <summary>
        /// 订单状态
        /// </summary>
        public System.Int32 OrderStatus 
        {
            get { return _OrderStatus; }
            set { _OrderStatus = value; }
        }
        
        /// <summary>
        /// 订单添加时间
        /// </summary>
        public System.DateTime OrderAddTime 
        {
            get { return _OrderAddTime; }
            set { _OrderAddTime = value; }
        }
        
        /// <summary>
        /// 订单审核时间
        /// </summary>
        public System.DateTime OrderAuditTime 
        {
            get { return _OrderAuditTime; }
            set { _OrderAuditTime = value; }
        }
        
        /// <summary>
        /// 订单付款时间
        /// </summary>
        public System.DateTime OrderPayTime 
        {
            get { return _OrderPayTime; }
            set { _OrderPayTime = value; }
        }
        
        /// <summary>
        /// 订单发货时间
        /// </summary>
        public System.DateTime GoodsSendTime 
        {
            get { return _GoodsSendTime; }
            set { _GoodsSendTime = value; }
        }
        
        /// <summary>
        /// 订单送达时间
        /// </summary>
        public System.DateTime GoodsServedTime 
        {
            get { return _GoodsServedTime; }
            set { _GoodsServedTime = value; }
        }
        
        /// <summary>
        /// 订单结束时间
        /// </summary>
        public System.DateTime OrderFinishTime 
        {
            get { return _OrderFinishTime; }
            set { _OrderFinishTime = value; }
        }
        
        /// <summary>
        /// 订单最后修改时间
        /// </summary>
        public System.DateTime LastModifyTime 
        {
            get { return _LastModifyTime; }
            set { _LastModifyTime = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_Orders";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,OrderNo,OrderType,UserID,UserName,AddOrderMethod,CouponsID,CouponsValue,GoodsTotalAmout,OrderShippingFee,InsuranceFee,OtherFee,OrderTotalAmount,Consignee,Country,Province,City,County,Address,PostCode,Phone,Mobile,ShippingID,ShippingName,ShippingNo,PayID,PayName,TradeNo,SendGoodsNeedNotice,NeedInvoice,InvoiceTitle,InvoiceContent,Invoiced,RecInvoice,Integral,CustomerMsg,Remark,OrderStatus,OrderAddTime,OrderAuditTime,OrderPayTime,GoodsSendTime,GoodsServedTime,OrderFinishTime,LastModifyTime";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("OrderNo");
                    
                    _listField.Add("OrderType");
                    
                    _listField.Add("UserID");
                    
                    _listField.Add("UserName");
                    
                    _listField.Add("AddOrderMethod");
                    
                    _listField.Add("CouponsID");
                    
                    _listField.Add("CouponsValue");
                    
                    _listField.Add("GoodsTotalAmout");
                    
                    _listField.Add("OrderShippingFee");
                    
                    _listField.Add("InsuranceFee");
                    
                    _listField.Add("OtherFee");
                    
                    _listField.Add("OrderTotalAmount");
                    
                    _listField.Add("Consignee");
                    
                    _listField.Add("Country");
                    
                    _listField.Add("Province");
                    
                    _listField.Add("City");
                    
                    _listField.Add("County");
                    
                    _listField.Add("Address");
                    
                    _listField.Add("PostCode");
                    
                    _listField.Add("Phone");
                    
                    _listField.Add("Mobile");
                    
                    _listField.Add("ShippingID");
                    
                    _listField.Add("ShippingName");
                    
                    _listField.Add("ShippingNo");
                    
                    _listField.Add("PayID");
                    
                    _listField.Add("PayName");
                    
                    _listField.Add("TradeNo");
                    
                    _listField.Add("SendGoodsNeedNotice");
                    
                    _listField.Add("NeedInvoice");
                    
                    _listField.Add("InvoiceTitle");
                    
                    _listField.Add("InvoiceContent");
                    
                    _listField.Add("Invoiced");
                    
                    _listField.Add("RecInvoice");
                    
                    _listField.Add("Integral");
                    
                    _listField.Add("CustomerMsg");
                    
                    _listField.Add("Remark");
                    
                    _listField.Add("OrderStatus");
                    
                    _listField.Add("OrderAddTime");
                    
                    _listField.Add("OrderAuditTime");
                    
                    _listField.Add("OrderPayTime");
                    
                    _listField.Add("GoodsSendTime");
                    
                    _listField.Add("GoodsServedTime");
                    
                    _listField.Add("OrderFinishTime");
                    
                    _listField.Add("LastModifyTime");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}