//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:54
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 实体类
    /// </summary>
    [Serializable]
    public partial class PayLogInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _OrderID=0;
        
        private System.String _OrderNo=string.Empty;
        
        private System.Int32 _PayID=0;
        
        private System.String _PayName=string.Empty;
        
        private System.String _PayType=string.Empty;
        
        private System.String _PayAccount=string.Empty;
        
        private System.String _TradeNo=string.Empty;
        
        private System.Decimal _PayAmount=0.0m;
        
        private System.String _Remark=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public PayLogInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 OrderID 
        {
            get { return _OrderID; }
            set { _OrderID = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String OrderNo 
        {
            get { return _OrderNo; }
            set { _OrderNo = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 PayID 
        {
            get { return _PayID; }
            set { _PayID = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String PayName 
        {
            get { return _PayName; }
            set { _PayName = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String PayType 
        {
            get { return _PayType; }
            set { _PayType = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String PayAccount 
        {
            get { return _PayAccount; }
            set { _PayAccount = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String TradeNo 
        {
            get { return _TradeNo; }
            set { _TradeNo = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Decimal PayAmount 
        {
            get { return _PayAmount; }
            set { _PayAmount = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String Remark 
        {
            get { return _Remark; }
            set { _Remark = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_PayLog";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,OrderID,OrderNo,PayID,PayName,PayType,PayAccount,TradeNo,PayAmount,Remark,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("OrderID");
                    
                    _listField.Add("OrderNo");
                    
                    _listField.Add("PayID");
                    
                    _listField.Add("PayName");
                    
                    _listField.Add("PayType");
                    
                    _listField.Add("PayAccount");
                    
                    _listField.Add("TradeNo");
                    
                    _listField.Add("PayAmount");
                    
                    _listField.Add("Remark");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}