//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:55
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 支付方式详情设置实体类
    /// </summary>
    [Serializable]
    public partial class PaymentSettingInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _PayID=0;
        
        private System.String _SettingKey=string.Empty;
        
        private System.String _Alias=string.Empty;
        
        private System.String _SettingValue=string.Empty;
        
        private System.String _Operator=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public PaymentSettingInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 支付方式ID
        /// </summary>
        public System.Int32 PayID 
        {
            get { return _PayID; }
            set { _PayID = value; }
        }
        
        /// <summary>
        /// 设置的键名称
        /// </summary>
        public System.String SettingKey 
        {
            get { return _SettingKey; }
            set { _SettingKey = value; }
        }
        
        /// <summary>
        /// 别名
        /// </summary>
        public System.String Alias 
        {
            get { return _Alias; }
            set { _Alias = value; }
        }
        
        /// <summary>
        /// 设置的值名称
        /// </summary>
        public System.String SettingValue 
        {
            get { return _SettingValue; }
            set { _SettingValue = value; }
        }
        
        /// <summary>
        /// 操作者
        /// </summary>
        public System.String Operator 
        {
            get { return _Operator; }
            set { _Operator = value; }
        }
        
        /// <summary>
        /// 创建日期
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_PaymentSetting";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,PayID,SettingKey,Alias,SettingValue,Operator,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("PayID");
                    
                    _listField.Add("SettingKey");
                    
                    _listField.Add("Alias");
                    
                    _listField.Add("SettingValue");
                    
                    _listField.Add("Operator");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}