//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2015-5-7 17:12:31
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 在线支付方式实体类
    /// </summary>
    [Serializable]
    public partial class PaymentInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _PayName=string.Empty;
        
        private System.String _PayCode=string.Empty;
        
        private System.String _PayType=string.Empty;
        
        private System.String _PayDesc=string.Empty;
        
        private System.String _OfficialSite=string.Empty;
        
        private System.String _PayLogo=string.Empty;
        
        private System.String _Config=string.Empty;
        
        private System.Boolean _IsOnline=false;
        
        private System.Boolean _IsUsing=false;
        
        private System.Int32 _Sort=0;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public PaymentInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 支付方式名称
        /// </summary>
        public System.String PayName 
        {
            get { return _PayName; }
            set { _PayName = value; }
        }
        
        /// <summary>
        /// 支付方式代号
        /// </summary>
        public System.String PayCode 
        {
            get { return _PayCode; }
            set { _PayCode = value; }
        }
        
        /// <summary>
        /// 支付种类
        /// </summary>
        public System.String PayType 
        {
            get { return _PayType; }
            set { _PayType = value; }
        }
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String PayDesc 
        {
            get { return _PayDesc; }
            set { _PayDesc = value; }
        }
        
        /// <summary>
        /// 官方网站
        /// </summary>
        public System.String OfficialSite 
        {
            get { return _OfficialSite; }
            set { _OfficialSite = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String PayLogo 
        {
            get { return _PayLogo; }
            set { _PayLogo = value; }
        }
        
        /// <summary>
        /// 需要配置的信息
        /// </summary>
        public System.String Config 
        {
            get { return _Config; }
            set { _Config = value; }
        }
        
        /// <summary>
        /// 是否在线支付
        /// </summary>
        public System.Boolean IsOnline 
        {
            get { return _IsOnline; }
            set { _IsOnline = value; }
        }
        
        /// <summary>
        /// 是否启用
        /// </summary>
        public System.Boolean IsUsing 
        {
            get { return _IsUsing; }
            set { _IsUsing = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 添加日期
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_Payment";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,PayName,PayCode,PayType,PayDesc,OfficialSite,PayLogo,Config,IsOnline,IsUsing,Sort,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("PayName");
                    
                    _listField.Add("PayCode");
                    
                    _listField.Add("PayType");
                    
                    _listField.Add("PayDesc");
                    
                    _listField.Add("OfficialSite");
                    
                    _listField.Add("PayLogo");
                    
                    _listField.Add("Config");
                    
                    _listField.Add("IsOnline");
                    
                    _listField.Add("IsUsing");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}