//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2015-7-24 16:37:13
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 邮费模板实体类
    /// </summary>
    [Serializable]
    public partial class PostageModelInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _ModelName=string.Empty;
        
        private System.String _ShortDesc=string.Empty;
        
        private System.String _RuleSet=string.Empty;
        
        private System.String _Creator=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public PostageModelInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 模板名称
        /// </summary>
        public System.String ModelName 
        {
            get { return _ModelName; }
            set { _ModelName = value; }
        }
        
        /// <summary>
        /// 说明
        /// </summary>
        public System.String ShortDesc 
        {
            get { return _ShortDesc; }
            set { _ShortDesc = value; }
        }
        
        /// <summary>
        /// 邮费规则
        /// </summary>
        public System.String RuleSet 
        {
            get { return _RuleSet; }
            set { _RuleSet = value; }
        }
        
        /// <summary>
        /// 创建者
        /// </summary>
        public System.String Creator 
        {
            get { return _Creator; }
            set { _Creator = value; }
        }
        
        /// <summary>
        /// 时间
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_PostageModel";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,ModelName,ShortDesc,RuleSet,Creator,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("ModelName");
                    
                    _listField.Add("ShortDesc");
                    
                    _listField.Add("RuleSet");
                    
                    _listField.Add("Creator");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}