//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:56
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 团购价格阶梯实体类
    /// </summary>
    [Serializable]
    public partial class PriceLadderInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _GrouponID=0;
        
        private System.String _GrouponName=string.Empty;
        
        private System.Int32 _JoinNum=0;
        
        private System.Decimal _Price=0.0m;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public PriceLadderInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 团购活动编号
        /// </summary>
        public System.Int32 GrouponID 
        {
            get { return _GrouponID; }
            set { _GrouponID = value; }
        }
        
        /// <summary>
        /// 团购活动名称
        /// </summary>
        public System.String GrouponName 
        {
            get { return _GrouponName; }
            set { _GrouponName = value; }
        }
        
        /// <summary>
        /// 参团人数量
        /// </summary>
        public System.Int32 JoinNum 
        {
            get { return _JoinNum; }
            set { _JoinNum = value; }
        }
        
        /// <summary>
        /// 享受的价格
        /// </summary>
        public System.Decimal Price 
        {
            get { return _Price; }
            set { _Price = value; }
        }
        
        /// <summary>
        /// 语言
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 时间
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_PriceLadder";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,GrouponID,GrouponName,JoinNum,Price,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("GrouponID");
                    
                    _listField.Add("GrouponName");
                    
                    _listField.Add("JoinNum");
                    
                    _listField.Add("Price");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}