//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:28
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 权限实体类
    /// </summary>
    [Serializable]
    public partial class PurviewInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _RoleID=0;
        
        private System.Int32 _ModuleID=0;
        
        private System.String _SourceCode=string.Empty;
        
        private System.String _OperateCode=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public PurviewInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 角色ID
        /// </summary>
        public System.Int32 RoleID 
        {
            get { return _RoleID; }
            set { _RoleID = value; }
        }
        
        /// <summary>
        /// 模块ID
        /// </summary>
        public System.Int32 ModuleID 
        {
            get { return _ModuleID; }
            set { _ModuleID = value; }
        }
        
        /// <summary>
        /// 资源代码
        /// </summary>
        public System.String SourceCode 
        {
            get { return _SourceCode; }
            set { _SourceCode = value; }
        }
        
        /// <summary>
        /// 操作代码
        /// </summary>
        public System.String OperateCode 
        {
            get { return _OperateCode; }
            set { _OperateCode = value; }
        }
        
        /// <summary>
        /// 创建日期
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_Purview";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,RoleID,ModuleID,SourceCode,OperateCode,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("RoleID");
                    
                    _listField.Add("ModuleID");
                    
                    _listField.Add("SourceCode");
                    
                    _listField.Add("OperateCode");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}