//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2015-7-24 16:37:11
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 退货记录实体类
    /// </summary>
    [Serializable]
    public partial class SalesRetInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _OrderNo=string.Empty;
        
        private System.String _ProductName=string.Empty;
        
        private System.String _Reason=string.Empty;
        
        private System.String _Operator=string.Empty;
        
        private System.Int32 _Status=0;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public SalesRetInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 订单编号
        /// </summary>
        public System.String OrderNo 
        {
            get { return _OrderNo; }
            set { _OrderNo = value; }
        }
        
        /// <summary>
        /// 商品名称
        /// </summary>
        public System.String ProductName 
        {
            get { return _ProductName; }
            set { _ProductName = value; }
        }
        
        /// <summary>
        /// 退货原因
        /// </summary>
        public System.String Reason 
        {
            get { return _Reason; }
            set { _Reason = value; }
        }
        
        /// <summary>
        /// 退货人
        /// </summary>
        public System.String Operator 
        {
            get { return _Operator; }
            set { _Operator = value; }
        }
        
        /// <summary>
        /// 状态
        /// </summary>
        public System.Int32 Status 
        {
            get { return _Status; }
            set { _Status = value; }
        }
        
        /// <summary>
        /// 时间
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_SalesRet";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,OrderNo,ProductName,Reason,Operator,Status,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("OrderNo");
                    
                    _listField.Add("ProductName");
                    
                    _listField.Add("Reason");
                    
                    _listField.Add("Operator");
                    
                    _listField.Add("Status");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}