//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:52:10
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 自定义设置分类实体类
    /// </summary>
    [Serializable]
    public partial class SettingCategoryInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _CateName=string.Empty;
        
        private System.String _CateDesc=string.Empty;
        
        private System.Int32 _Sort=0;
        
        private System.Boolean _IsUsing=false;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public SettingCategoryInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 分类名称
        /// </summary>
        public System.String CateName 
        {
            get { return _CateName; }
            set { _CateName = value; }
        }
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String CateDesc 
        {
            get { return _CateDesc; }
            set { _CateDesc = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 是否启用
        /// </summary>
        public System.Boolean IsUsing 
        {
            get { return _IsUsing; }
            set { _IsUsing = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "sys_SettingCategory";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,CateName,CateDesc,Sort,IsUsing,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("CateName");
                    
                    _listField.Add("CateDesc");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("IsUsing");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}