//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:52:06
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 专题实体类
    /// </summary>
    [Serializable]
    public partial class ShopSpecialInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _Title=string.Empty;
        
        private System.String _ProIDList=string.Empty;
        
        private System.String _ShowPic=string.Empty;
        
        private System.String _Detail=string.Empty;
        
        private System.Int32 _Sort=0;
        
        private System.Boolean _IsAudit=false;
        
        private System.String _Lang=string.Empty;
        
        private System.String _Creator=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public ShopSpecialInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 标题
        /// </summary>
        public System.String Title 
        {
            get { return _Title; }
            set { _Title = value; }
        }
        
        /// <summary>
        /// 产品ID集合
        /// </summary>
        public System.String ProIDList 
        {
            get { return _ProIDList; }
            set { _ProIDList = value; }
        }
        
        /// <summary>
        /// 图片
        /// </summary>
        public System.String ShowPic 
        {
            get { return _ShowPic; }
            set { _ShowPic = value; }
        }
        
        /// <summary>
        /// 详情
        /// </summary>
        public System.String Detail 
        {
            get { return _Detail; }
            set { _Detail = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 是否审核
        /// </summary>
        public System.Boolean IsAudit 
        {
            get { return _IsAudit; }
            set { _IsAudit = value; }
        }
        
        /// <summary>
        /// 语言版本
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 创建者
        /// </summary>
        public System.String Creator 
        {
            get { return _Creator; }
            set { _Creator = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_ShopSpecial";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,Title,ProIDList,ShowPic,Detail,Sort,IsAudit,Lang,Creator,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("Title");
                    
                    _listField.Add("ProIDList");
                    
                    _listField.Add("ShowPic");
                    
                    _listField.Add("Detail");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("IsAudit");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("Creator");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}