//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:30
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 标准化网站模板实体类
    /// </summary>
    [Serializable]
    public partial class SiteTemplateInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _TemplateName=string.Empty;
        
        private System.String _ShowPic=string.Empty;
        
        private System.String _TemplatePath=string.Empty;
        
        private System.String _HomePage=string.Empty;
        
        private System.String _TemplateDesc=string.Empty;
        
        private System.Boolean _IsAudit=false;
        
        private System.Boolean _IsExists=false;
        
        private System.String _Author=string.Empty;
        
        private System.String _CopyRight=string.Empty;
        
        private System.Boolean _IsDefault=false;
        
        private System.Int32 _Sort=0;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public SiteTemplateInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 模板名称
        /// </summary>
        public System.String TemplateName 
        {
            get { return _TemplateName; }
            set { _TemplateName = value; }
        }
        
        /// <summary>
        /// 展示图片
        /// </summary>
        public System.String ShowPic 
        {
            get { return _ShowPic; }
            set { _ShowPic = value; }
        }
        
        /// <summary>
        /// 模板路径
        /// </summary>
        public System.String TemplatePath 
        {
            get { return _TemplatePath; }
            set { _TemplatePath = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String HomePage 
        {
            get { return _HomePage; }
            set { _HomePage = value; }
        }
        
        /// <summary>
        /// 说明与描述
        /// </summary>
        public System.String TemplateDesc 
        {
            get { return _TemplateDesc; }
            set { _TemplateDesc = value; }
        }
        
        /// <summary>
        /// 是否审核
        /// </summary>
        public System.Boolean IsAudit 
        {
            get { return _IsAudit; }
            set { _IsAudit = value; }
        }
        
        /// <summary>
        /// 是否可用/存在
        /// </summary>
        public System.Boolean IsExists 
        {
            get { return _IsExists; }
            set { _IsExists = value; }
        }
        
        /// <summary>
        /// 模板作者
        /// </summary>
        public System.String Author 
        {
            get { return _Author; }
            set { _Author = value; }
        }
        
        /// <summary>
        /// 模板版权信息
        /// </summary>
        public System.String CopyRight 
        {
            get { return _CopyRight; }
            set { _CopyRight = value; }
        }
        
        /// <summary>
        /// 是否默认设置
        /// </summary>
        public System.Boolean IsDefault 
        {
            get { return _IsDefault; }
            set { _IsDefault = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 添加时间
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_SiteTemplate";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,TemplateName,ShowPic,TemplatePath,HomePage,TemplateDesc,IsAudit,IsExists,Author,CopyRight,IsDefault,Sort,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("TemplateName");
                    
                    _listField.Add("ShowPic");
                    
                    _listField.Add("TemplatePath");
                    
                    _listField.Add("HomePage");
                    
                    _listField.Add("TemplateDesc");
                    
                    _listField.Add("IsAudit");
                    
                    _listField.Add("IsExists");
                    
                    _listField.Add("Author");
                    
                    _listField.Add("CopyRight");
                    
                    _listField.Add("IsDefault");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}