//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2015-12-9 15:02:47
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 短信发送表实体类
    /// </summary>
    [Serializable]
    public partial class SMSInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _SMSMob=string.Empty;
        
        private System.String _SMSText=string.Empty;
        
        private System.String _SMSType=string.Empty;
        
        private System.String _ValidateCode=string.Empty;
        
        private System.Int32 _ReciverID=0;
        
        private System.String _ReciverName=string.Empty;
        
        private System.Int32 _Status=0;
        
        private System.String _ReturnMsg=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public SMSInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 手机号码(11位,多个手机用逗号间隔)
        /// </summary>
        public System.String SMSMob 
        {
            get { return _SMSMob; }
            set { _SMSMob = value; }
        }
        
        /// <summary>
        /// 发送内容
        /// </summary>
        public System.String SMSText 
        {
            get { return _SMSText; }
            set { _SMSText = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String SMSType 
        {
            get { return _SMSType; }
            set { _SMSType = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String ValidateCode 
        {
            get { return _ValidateCode; }
            set { _ValidateCode = value; }
        }
        
        /// <summary>
        /// 接收者ID
        /// </summary>
        public System.Int32 ReciverID 
        {
            get { return _ReciverID; }
            set { _ReciverID = value; }
        }
        
        /// <summary>
        /// 接收者姓名
        /// </summary>
        public System.String ReciverName 
        {
            get { return _ReciverName; }
            set { _ReciverName = value; }
        }
        
        /// <summary>
        /// 状态(是否发送成功)
        /// </summary>
        public System.Int32 Status 
        {
            get { return _Status; }
            set { _Status = value; }
        }
        
        /// <summary>
        /// 返回信息
        /// </summary>
        public System.String ReturnMsg 
        {
            get { return _ReturnMsg; }
            set { _ReturnMsg = value; }
        }
        
        /// <summary>
        /// 操作时间
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_SMS";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,SMSMob,SMSText,SMSType,ValidateCode,ReciverID,ReciverName,Status,ReturnMsg,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("SMSMob");
                    
                    _listField.Add("SMSText");
                    
                    _listField.Add("SMSType");
                    
                    _listField.Add("ValidateCode");
                    
                    _listField.Add("ReciverID");
                    
                    _listField.Add("ReciverName");
                    
                    _listField.Add("Status");
                    
                    _listField.Add("ReturnMsg");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}