//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:32
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 标签实体类
    /// </summary>
    [Serializable]
    public partial class TagsInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _TagName=string.Empty;
        
        private System.String _TagUrl=string.Empty;
        
        private System.Int32 _TagIndex=0;
        
        private System.String _Remark=string.Empty;
        
        private System.Boolean _IsTop=false;
        
        private System.Boolean _IsRecommend=false;
        
        private System.Int32 _Sort=0;
        
        private System.String _Lang=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public TagsInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 标签名称
        /// </summary>
        public System.String TagName 
        {
            get { return _TagName; }
            set { _TagName = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String TagUrl 
        {
            get { return _TagUrl; }
            set { _TagUrl = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32 TagIndex 
        {
            get { return _TagIndex; }
            set { _TagIndex = value; }
        }
        
        /// <summary>
        /// 备注
        /// </summary>
        public System.String Remark 
        {
            get { return _Remark; }
            set { _Remark = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean IsTop 
        {
            get { return _IsTop; }
            set { _IsTop = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean IsRecommend 
        {
            get { return _IsRecommend; }
            set { _IsRecommend = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 语言版本
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "shop_Tags";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,TagName,TagUrl,TagIndex,Remark,IsTop,IsRecommend,Sort,Lang,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("TagName");
                    
                    _listField.Add("TagUrl");
                    
                    _listField.Add("TagIndex");
                    
                    _listField.Add("Remark");
                    
                    _listField.Add("IsTop");
                    
                    _listField.Add("IsRecommend");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}