//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 会员等级实体类
    /// </summary>
    [Serializable]
    public partial class UserLevelInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _LevelName=string.Empty;
        
        private System.Int32 _Integral=0;
        
        private System.Double _Discount=0.0d;
        
        private System.String _LevelDesc=string.Empty;
        
        private System.Int32 _Sort=0;
        
        private System.DateTime _LastModifyDate=new DateTime(1900, 1, 1);
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public UserLevelInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 等级名称
        /// </summary>
        public System.String LevelName 
        {
            get { return _LevelName; }
            set { _LevelName = value; }
        }
        
        /// <summary>
        /// 积分额
        /// </summary>
        public System.Int32 Integral 
        {
            get { return _Integral; }
            set { _Integral = value; }
        }
        
        /// <summary>
        /// 等级优惠
        /// </summary>
        public System.Double Discount 
        {
            get { return _Discount; }
            set { _Discount = value; }
        }
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String LevelDesc 
        {
            get { return _LevelDesc; }
            set { _LevelDesc = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 最后修改时间
        /// </summary>
        public System.DateTime LastModifyDate 
        {
            get { return _LastModifyDate; }
            set { _LastModifyDate = value; }
        }
        
        /// <summary>
        /// 创建日期
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_UserLevel";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,LevelName,Integral,Discount,LevelDesc,Sort,LastModifyDate,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("LevelName");
                    
                    _listField.Add("Integral");
                    
                    _listField.Add("Discount");
                    
                    _listField.Add("LevelDesc");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("LastModifyDate");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}