//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:38
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 会员组实体类
    /// </summary>
    [Serializable]
    public partial class UserGroupInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.String _GroupName=string.Empty;
        
        private System.String _TableName=string.Empty;
        
        private System.String _GroupDesc=string.Empty;
        
        private System.Int32 _Sort=0;
        
        private System.String _Creator=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public UserGroupInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 组名称
        /// </summary>
        public System.String GroupName 
        {
            get { return _GroupName; }
            set { _GroupName = value; }
        }
        
        /// <summary>
        /// 扩展表名
        /// </summary>
        public System.String TableName 
        {
            get { return _TableName; }
            set { _TableName = value; }
        }
        
        /// <summary>
        /// 描述
        /// </summary>
        public System.String GroupDesc 
        {
            get { return _GroupDesc; }
            set { _GroupDesc = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String Creator 
        {
            get { return _Creator; }
            set { _Creator = value; }
        }
        
        /// <summary>
        /// 自动时间戳
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_UserGroup";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,GroupName,TableName,GroupDesc,Sort,Creator,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("GroupName");
                    
                    _listField.Add("TableName");
                    
                    _listField.Add("GroupDesc");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("Creator");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}