//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2015-12-15 14:41:54
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 会员实体类
    /// </summary>
    [Serializable]
    public partial class UserInfo : JObject, IEntity
    {
        private int _AutoID = 0;

        private string _UserName = string.Empty;

        private int _GroupID = 0;

        private int _LevelID = 0;

        private string _Password = string.Empty;

        private string _Email = string.Empty;

        private string _Mobile = string.Empty;

        private decimal _Amount = 0.0m;

        private int _Integral = 0;

        private int _FileSpace = 0;

        private string _CertType = string.Empty;

        private string _CertNo = string.Empty;

        private string _NickName = string.Empty;

        private string _RealName = string.Empty;

        private string _Gender = string.Empty;

        private DateTime _Birthday = new DateTime(1900, 1, 1);

        private string _HeaderPhoto = string.Empty;

        private decimal _CreditLine = 0.0m;

        private string _Area = string.Empty;

        private string _Country = string.Empty;

        private string _Province = string.Empty;

        private string _City = string.Empty;

        private string _County = string.Empty;

        private string _Address = string.Empty;

        private string _PostCode = string.Empty;

        private string _TelePhone = string.Empty;

        private string _Remark = string.Empty;

        private bool _IsThirdLoginReg = false;

        private int _Status = 0;

        private int _Sort = 0;

        private int _LoginCount = 0;

        private DateTime _LastLoginTime = new DateTime(1900, 1, 1);

        private string _LastLoginIP = string.Empty;

        private DateTime _AutoTimeStamp = new DateTime(1900, 1, 1);

        private static List<string> _listField = null;

        

        public int AutoID
        {
            get
            {
                return this._AutoID;
            }
            set
            {
                this._AutoID = value;
            }
        }

        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this._UserName = value;
            }
        }

        public int GroupID
        {
            get
            {
                return this._GroupID;
            }
            set
            {
                this._GroupID = value;
            }
        }

        public int LevelID
        {
            get
            {
                return this._LevelID;
            }
            set
            {
                this._LevelID = value;
            }
        }

        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this._Password = value;
            }
        }

        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this._Email = value;
            }
        }

        public string Mobile
        {
            get
            {
                return this._Mobile;
            }
            set
            {
                this._Mobile = value;
            }
        }

        public decimal Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this._Amount = value;
            }
        }

        public int Integral
        {
            get
            {
                return this._Integral;
            }
            set
            {
                this._Integral = value;
            }
        }

        public int FileSpace
        {
            get
            {
                return this._FileSpace;
            }
            set
            {
                this._FileSpace = value;
            }
        }

        public string CertType
        {
            get
            {
                return this._CertType;
            }
            set
            {
                this._CertType = value;
            }
        }

        public string CertNo
        {
            get
            {
                return this._CertNo;
            }
            set
            {
                this._CertNo = value;
            }
        }

        public string NickName
        {
            get
            {
                return this._NickName;
            }
            set
            {
                this._NickName = value;
            }
        }

        public string RealName
        {
            get
            {
                return this._RealName;
            }
            set
            {
                this._RealName = value;
            }
        }

        public string Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this._Gender = value;
            }
        }

        public DateTime Birthday
        {
            get
            {
                return this._Birthday;
            }
            set
            {
                this._Birthday = value;
            }
        }

        public string HeaderPhoto
        {
            get
            {
                return this._HeaderPhoto;
            }
            set
            {
                this._HeaderPhoto = value;
            }
        }

        public decimal CreditLine
        {
            get
            {
                return this._CreditLine;
            }
            set
            {
                this._CreditLine = value;
            }
        }

        public string Area
        {
            get
            {
                return this._Area;
            }
            set
            {
                this._Area = value;
            }
        }

        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this._Country = value;
            }
        }

        public string Province
        {
            get
            {
                return this._Province;
            }
            set
            {
                this._Province = value;
            }
        }

        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this._City = value;
            }
        }

        public string County
        {
            get
            {
                return this._County;
            }
            set
            {
                this._County = value;
            }
        }

        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this._Address = value;
            }
        }

        public string PostCode
        {
            get
            {
                return this._PostCode;
            }
            set
            {
                this._PostCode = value;
            }
        }

        public string TelePhone
        {
            get
            {
                return this._TelePhone;
            }
            set
            {
                this._TelePhone = value;
            }
        }

        public string Remark
        {
            get
            {
                return this._Remark;
            }
            set
            {
                this._Remark = value;
            }
        }

        public bool IsThirdLoginReg
        {
            get
            {
                return this._IsThirdLoginReg;
            }
            set
            {
                this._IsThirdLoginReg = value;
            }
        }

        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this._Status = value;
            }
        }

        public int Sort
        {
            get
            {
                return this._Sort;
            }
            set
            {
                this._Sort = value;
            }
        }

        public int LoginCount
        {
            get
            {
                return this._LoginCount;
            }
            set
            {
                this._LoginCount = value;
            }
        }

        public DateTime LastLoginTime
        {
            get
            {
                return this._LastLoginTime;
            }
            set
            {
                this._LastLoginTime = value;
            }
        }

        public string LastLoginIP
        {
            get
            {
                return this._LastLoginIP;
            }
            set
            {
                this._LastLoginIP = value;
            }
        }

        public DateTime AutoTimeStamp
        {
            get
            {
                return this._AutoTimeStamp;
            }
            set
            {
                this._AutoTimeStamp = value;
            }
        }

        public string DBTableName
        {
            get
            {
                return "cms_User";
            }
        }

        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }

        public string Fields
        {
            get
            {
                return "AutoID,UserName,GroupID,LevelID,Password,Email,Mobile,Amount,Integral,FileSpace,CertType,CertNo,NickName,RealName,Gender,Birthday,HeaderPhoto,CreditLine,Area,Country,Province,City,County,Address,PostCode,TelePhone,Remark,IsThirdLoginReg,Status,Sort,LoginCount,LastLoginTime,LastLoginIP,AutoTimeStamp";
            }
        }

        public List<string> FieldList
        {
            get
            {
                if (UserInfo._listField == null)
                {
                    UserInfo._listField = new List<string>();
                    UserInfo._listField.Add("AutoID");
                    UserInfo._listField.Add("UserName");
                    UserInfo._listField.Add("GroupID");
                    UserInfo._listField.Add("LevelID");
                    UserInfo._listField.Add("Password");
                    UserInfo._listField.Add("Email");
                    UserInfo._listField.Add("Mobile");
                    UserInfo._listField.Add("Amount");
                    UserInfo._listField.Add("Integral");
                    UserInfo._listField.Add("FileSpace");
                    UserInfo._listField.Add("CertType");
                    UserInfo._listField.Add("CertNo");
                    UserInfo._listField.Add("NickName");
                    UserInfo._listField.Add("RealName");
                    UserInfo._listField.Add("Gender");
                    UserInfo._listField.Add("Birthday");
                    UserInfo._listField.Add("HeaderPhoto");
                    UserInfo._listField.Add("CreditLine");
                    UserInfo._listField.Add("Area");
                    UserInfo._listField.Add("Country");
                    UserInfo._listField.Add("Province");
                    UserInfo._listField.Add("City");
                    UserInfo._listField.Add("County");
                    UserInfo._listField.Add("Address");
                    UserInfo._listField.Add("PostCode");
                    UserInfo._listField.Add("TelePhone");
                    UserInfo._listField.Add("Remark");
                    UserInfo._listField.Add("IsThirdLoginReg");
                    UserInfo._listField.Add("Status");
                    UserInfo._listField.Add("Sort");
                    UserInfo._listField.Add("LoginCount");
                    UserInfo._listField.Add("LastLoginTime");
                    UserInfo._listField.Add("LastLoginIP");
                    UserInfo._listField.Add("AutoTimeStamp");
                }
                return UserInfo._listField;
            }
        }

        
    }
}