//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:52:13
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 软件信息实体类
    /// </summary>
    [Serializable]
    public partial class VerInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.String _SoftName=string.Empty;
        
        private System.String _LicTimeStart=string.Empty;
        
        private System.String _LicTimeEnd=string.Empty;
        
        private System.String _UpdateUrl=string.Empty;
        
        private System.String _Ver=string.Empty;
        
        private System.String _Author=string.Empty;
        
        private System.String _Company=string.Empty;
        
        private System.String _Address=string.Empty;
        
        private System.String _PostCode=string.Empty;
        
        private System.String _CopyRight=string.Empty;
        
        private System.String _Brand=string.Empty;
        
        private System.String _CustomerID=string.Empty;
        
        private System.String _CustomerName=string.Empty;
        
        private System.String _CustomerAddr=string.Empty;
        
        private System.String _Contact=string.Empty;
        
        private System.String _Mobile=string.Empty;
        
        private System.String _Email=string.Empty;
        
        private System.String _ProjectStart=string.Empty;
        
        private System.String _ProjectEnd=string.Empty;
        
        private System.Int64 _SiteCapacity=0;
        
        private System.Int32 _NodeLimit=0;
        
        private System.Int32 _ContentLimit=0;
        
        private System.Int32 _CategoryLimit=0;
        
        private System.Int32 _ProductLimit=0;
        
        private System.DateTime _RegTime=new DateTime(1900, 1, 1);
        
        private System.String _DesktopSet=string.Empty;
        
        private System.String _Remark=string.Empty;
        
        private System.DateTime _LastUpdateTime=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public VerInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 软件名称
        /// </summary>
        public System.String SoftName 
        {
            get { return _SoftName; }
            set { _SoftName = value; }
        }
        
        /// <summary>
        /// 有效期开始时间
        /// </summary>
        public System.String LicTimeStart 
        {
            get { return _LicTimeStart; }
            set { _LicTimeStart = value; }
        }
        
        /// <summary>
        /// 有效期截止时间
        /// </summary>
        public System.String LicTimeEnd 
        {
            get { return _LicTimeEnd; }
            set { _LicTimeEnd = value; }
        }
        
        /// <summary>
        /// 软件更新地址
        /// </summary>
        public System.String UpdateUrl 
        {
            get { return _UpdateUrl; }
            set { _UpdateUrl = value; }
        }
        
        /// <summary>
        /// 版本号
        /// </summary>
        public System.String Ver 
        {
            get { return _Ver; }
            set { _Ver = value; }
        }
        
        /// <summary>
        /// 作者
        /// </summary>
        public System.String Author 
        {
            get { return _Author; }
            set { _Author = value; }
        }
        
        /// <summary>
        /// 开发公司
        /// </summary>
        public System.String Company 
        {
            get { return _Company; }
            set { _Company = value; }
        }
        
        /// <summary>
        /// 地址
        /// </summary>
        public System.String Address 
        {
            get { return _Address; }
            set { _Address = value; }
        }
        
        /// <summary>
        /// 邮编
        /// </summary>
        public System.String PostCode 
        {
            get { return _PostCode; }
            set { _PostCode = value; }
        }
        
        /// <summary>
        /// 版权
        /// </summary>
        public System.String CopyRight 
        {
            get { return _CopyRight; }
            set { _CopyRight = value; }
        }
        
        /// <summary>
        /// 商标
        /// </summary>
        public System.String Brand 
        {
            get { return _Brand; }
            set { _Brand = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String CustomerID 
        {
            get { return _CustomerID; }
            set { _CustomerID = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String CustomerName 
        {
            get { return _CustomerName; }
            set { _CustomerName = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String CustomerAddr 
        {
            get { return _CustomerAddr; }
            set { _CustomerAddr = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String Contact 
        {
            get { return _Contact; }
            set { _Contact = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String Mobile 
        {
            get { return _Mobile; }
            set { _Mobile = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String Email 
        {
            get { return _Email; }
            set { _Email = value; }
        }
        
        /// <summary>
        /// 项目开始日期
        /// </summary>
        public System.String ProjectStart 
        {
            get { return _ProjectStart; }
            set { _ProjectStart = value; }
        }
        
        /// <summary>
        /// 项目结束日期
        /// </summary>
        public System.String ProjectEnd 
        {
            get { return _ProjectEnd; }
            set { _ProjectEnd = value; }
        }
        
        /// <summary>
        /// 站点容量
        /// </summary>
        public System.Int64 SiteCapacity 
        {
            get { return _SiteCapacity; }
            set { _SiteCapacity = value; }
        }
        
        /// <summary>
        /// 栏目限制
        /// </summary>
        public System.Int32 NodeLimit 
        {
            get { return _NodeLimit; }
            set { _NodeLimit = value; }
        }
        
        /// <summary>
        /// 内容限制
        /// </summary>
        public System.Int32 ContentLimit 
        {
            get { return _ContentLimit; }
            set { _ContentLimit = value; }
        }
        
        /// <summary>
        /// 产品分类限制
        /// </summary>
        public System.Int32 CategoryLimit 
        {
            get { return _CategoryLimit; }
            set { _CategoryLimit = value; }
        }
        
        /// <summary>
        /// 产品限制
        /// </summary>
        public System.Int32 ProductLimit 
        {
            get { return _ProductLimit; }
            set { _ProductLimit = value; }
        }
        
        /// <summary>
        /// 注册时间、开通时间
        /// </summary>
        public System.DateTime RegTime 
        {
            get { return _RegTime; }
            set { _RegTime = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String DesktopSet 
        {
            get { return _DesktopSet; }
            set { _DesktopSet = value; }
        }
        
        /// <summary>
        /// 说明
        /// </summary>
        public System.String Remark 
        {
            get { return _Remark; }
            set { _Remark = value; }
        }
        
        /// <summary>
        /// 最后更新日期
        /// </summary>
        public System.DateTime LastUpdateTime 
        {
            get { return _LastUpdateTime; }
            set { _LastUpdateTime = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "sys_Ver";
            }
        }
        public string PKName
        {
            get
            {
                return "SoftName";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "SoftName,LicTimeStart,LicTimeEnd,UpdateUrl,Ver,Author,Company,Address,PostCode,CopyRight,Brand,CustomerID,CustomerName,CustomerAddr,Contact,Mobile,Email,ProjectStart,ProjectEnd,SiteCapacity,NodeLimit,ContentLimit,CategoryLimit,ProductLimit,RegTime,DesktopSet,Remark,LastUpdateTime";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("SoftName");
                    
                    _listField.Add("LicTimeStart");
                    
                    _listField.Add("LicTimeEnd");
                    
                    _listField.Add("UpdateUrl");
                    
                    _listField.Add("Ver");
                    
                    _listField.Add("Author");
                    
                    _listField.Add("Company");
                    
                    _listField.Add("Address");
                    
                    _listField.Add("PostCode");
                    
                    _listField.Add("CopyRight");
                    
                    _listField.Add("Brand");
                    
                    _listField.Add("CustomerID");
                    
                    _listField.Add("CustomerName");
                    
                    _listField.Add("CustomerAddr");
                    
                    _listField.Add("Contact");
                    
                    _listField.Add("Mobile");
                    
                    _listField.Add("Email");
                    
                    _listField.Add("ProjectStart");
                    
                    _listField.Add("ProjectEnd");
                    
                    _listField.Add("SiteCapacity");
                    
                    _listField.Add("NodeLimit");
                    
                    _listField.Add("ContentLimit");
                    
                    _listField.Add("CategoryLimit");
                    
                    _listField.Add("ProductLimit");
                    
                    _listField.Add("RegTime");
                    
                    _listField.Add("DesktopSet");
                    
                    _listField.Add("Remark");
                    
                    _listField.Add("LastUpdateTime");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}