//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     Author:liqiang665@163.com www.sz3w.net
//     生成时间为:2014-9-1 15:51:41
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SinGooCMS.Entity 
{
    /// <summary>
    /// 投票项实体类
    /// </summary>
    [Serializable]
    public partial class VoteItemInfo : JObject, IEntity
    {        
        #region 私有字段
        
        private System.Int32 _AutoID=0;
        
        private System.Int32 _VoteID=0;
        
        private System.String _VoteOption=string.Empty;
        
        private System.Int32 _VoteNum=0;
        
        private System.Int32 _Sort=0;
        
        private System.String _Lang=string.Empty;
        
        private System.String _Creator=string.Empty;
        
        private System.DateTime _AutoTimeStamp=new DateTime(1900, 1, 1);
        
        private static List<System.String> _listField = null;
        #endregion

        /// <summary>
        /// 默认构造函数
        /// </summary>
        public VoteItemInfo() 
        {
            //
        }
        
        #region 公共属性
        
        /// <summary>
        /// 主键
        /// </summary>
        public System.Int32 AutoID 
        {
            get { return _AutoID; }
            set { _AutoID = value; }
        }
        
        /// <summary>
        /// 投票ID
        /// </summary>
        public System.Int32 VoteID 
        {
            get { return _VoteID; }
            set { _VoteID = value; }
        }
        
        /// <summary>
        /// 内容
        /// </summary>
        public System.String VoteOption 
        {
            get { return _VoteOption; }
            set { _VoteOption = value; }
        }
        
        /// <summary>
        /// 投票数
        /// </summary>
        public System.Int32 VoteNum 
        {
            get { return _VoteNum; }
            set { _VoteNum = value; }
        }
        
        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32 Sort 
        {
            get { return _Sort; }
            set { _Sort = value; }
        }
        
        /// <summary>
        /// 语言版本
        /// </summary>
        public System.String Lang 
        {
            get { return _Lang; }
            set { _Lang = value; }
        }
        
        /// <summary>
        /// 创建者
        /// </summary>
        public System.String Creator 
        {
            get { return _Creator; }
            set { _Creator = value; }
        }
        
        /// <summary>
        /// 创建时间
        /// </summary>
        public System.DateTime AutoTimeStamp 
        {
            get { return _AutoTimeStamp; }
            set { _AutoTimeStamp = value; }
        }
                
        /// <summary>
        /// 数据库表名
        /// </summary>
        public string DBTableName
        {
            get
            {
                return "cms_VoteItem";
            }
        }
        public string PKName
        {
            get
            {
                return "AutoID";
            }
        }
        /// <summary>
        /// 整合字段为字符串并输出
        /// </summary>
        /// <returns></returns>
        public string Fields
        {
            get
            {
                return "AutoID,VoteID,VoteOption,VoteNum,Sort,Lang,Creator,AutoTimeStamp";
            }            
        }
        /// <summary>
        /// 数据表字段
        /// </summary>
        public List<System.String> FieldList
        {
            get
            {
                if (_listField == null)
                {     
                    _listField = new List<System.String>();          
                    
                    _listField.Add("AutoID");
                    
                    _listField.Add("VoteID");
                    
                    _listField.Add("VoteOption");
                    
                    _listField.Add("VoteNum");
                    
                    _listField.Add("Sort");
                    
                    _listField.Add("Lang");
                    
                    _listField.Add("Creator");
                    
                    _listField.Add("AutoTimeStamp");
                    
                }

                return _listField;
            }
        }
        
        #endregion
        
    }
}